### ISSUE TITLE
WARN[0003] Failed to get config digest from manifest.

### ISSUE THREAD

**Issue by wjtien** [regclient/regclient#105]
**Version：**
{
  "VCSRef": "0cb9b4c8bc5394be47432b3c884ff7933d40d0b8",
  "VCSTag": "v0.3.9"
}

**Command：**
`regctl image copy quay.io/cilium/cilium-etcd-operator:v2.0.7 myprivate.registry/cilium/cilium-etcd-operator:v2.0.7
`
**Error：**
WARN[0003] Failed to get config digest from manifest     err="Config digest not available for media type application/vnd.docker.distribution.manifest.v1+prettyjws" ref="quay.io/cilium/cilium-etcd-operator:v2.0.7"
Failed to get config digest for quay.io/cilium/cilium-etcd-operator:v2.0.7: Config digest not available for media type application/vnd.docker.distribution.manifest.v1+prettyjws

may be  media type **application/vnd.docker.distribution.manifest.v1+prettyjws** in the current regclient version  unsupported...

**Comment by sudo-bmitch** [comment]
These warnings shouldn't show in current releases. Thanks for reporting this!
