### ISSUE TITLE
Ability to get manifests for all architectures

### ISSUE THREAD

**Issue by mikesir87** [regclient/regclient#107]
I’m looking at building some tooling that needs the data from manifests, but for all architectures. And, many times, I might not know what architectures to ask for. 

Any chance we could support a `--platform=all` and we get an array of manifests back for each architecture?  Or if you have other ideas, I’m game too!

**Comment by mikesir87** [comment]
Ok. I’m partially an idiot, in that you have `--list`. But, since it isn’t JSON format, it’s a little trickier to work with the output there. Any chance we could have a JSON-formatted list somehow?

**Comment by sudo-bmitch** [comment]
Hey @mikesir87, there's a few formats that can help, you can use `--format '{{ json . }}'` to convert to json, or `--format '{{ jsonPretty . }}'` for something that's got white space for readability, and the original manifest is itself json, so you can use `--format raw-body` that will output the unmodified manifest (also useful for checking sha256 digest).

The result is:

```
$ regctl manifest get --list regclient/regsync --format '{{ jsonPretty . }}'
{
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "digest": "sha256:f6e02db8dd1b71d30142d33189644932f5cadc8b390bf65ae54b7fade4dd44c7",
      "size": 1152,
      "platform": {
        "architecture": "386",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "digest": "sha256:ebfb91880aa17894a643e2494767d1692372d4d8ba47b137773a8e1dfe94f29b",
      "size": 1152,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
...
```

The format is a Go template, so you can also get fancier:

```
$ regctl manifest get --list localhost:5000/regclient/regctl --format '{{ range $k, $v := .Manifests }}{{ if eq $v.Platform.Variant "" }}{{ printf "%s/%s: %s\n" $v.Platform.OS $v.Platform.Architecture $v.Digest }}{{ else }}{{ printf "%s/%s/%s: %s\n" $v.Platform.OS $v.Platform.Architecture $v.Platform.Variant $v.Digest }}{{ end }}{{ end }}'
linux/386: sha256:69168abe0494a1f1e619725d23a8f85cb156a8986f342c7dc86915b551f5a711
linux/amd64: sha256:41b9947d8f19e154a5415c88ef71b851d37fa3ceb1de56ffe88d1b616ce503d9
linux/arm/v6: sha256:e8baa0ddeed304ed91e91f155392462fcfab79df67f1052f92a377305dd521b6
linux/arm/v7: sha256:5536e52b2508b905c7f37bf120435c3c75684bab53c04467b61904be1febe5f8
linux/arm64: sha256:b302f648065bb2ba542dc75167db065781f296ef72bb504585d652b27b5079ad
linux/ppc64le: sha256:2d6a26eeb5a58c3c2534470f201b471778cc2ed37352775c9632e60880339e24
linux/s390x: sha256:201dd5b2dcc8793566b3d2cfa4d32eb3963028d20cc7befb3260de6d7ceac8a4
```

**Comment by mikesir87** [comment]
Super cool! As probably is clear, I haven't spent enough time with Go templating. 😂 

This should do the trick for me. I'll be sure to share what I'm playing with soon. 😉
