### ISSUE TITLE
[Issue] 0.4 not working with private registry

### ISSUE THREAD

**Issue by dmarteau** [regclient/regclient#178]
## Context:
 * private registry with root CA in /etc/docker/certs.d/
 * Working correctly with curl
 * Working correctly with regctl 0.3

When using regctl 0.4 I have the following error on the command `regctl repo ls registry.snap.lizlan:5000`
```
WARN[0000] Sleeping for backoff                          Host="registry.snap.lizlan:5000" Seconds=1.9999968909999999
WARN[0002] Sleeping for backoff                          Host="registry.snap.lizlan:5000" Seconds=3.999993341
failed to list repositories for registry.snap.lizlan:5000: Get "https://registry.snap.lizlan:5000/v2/_catalog": x509: certificate signed by unknown authority
```

### Expected Behavior

Working withour error as with regctl 0.3 in the same context.

### Steps To Reproduce

* Run private registry using self-signed Authority CA
* Install your registry CA in the appropiriate location: `/etc/docker/certs.d/<registri_uri>/ca.crt
* Check access to the registry (docker, curl etc...)
* Run `repo ls ...`  with regctl 0.4 

### Version

```text
{
  "VCSRef": "9546658ede6901191b9692a7f720c37150940ddd",
  "VCSTag": "v0.4.0"
}

```

### Environment

* Linux  x86_64  (buster, bullseye)
* Tested with both docker image and binary.
* Docker registry `registry:2.7.1`
 
### What else

Work as expected with regctl v0.3

**Comment by sudo-bmitch** [comment]
Thank you for catching this! I've got a fix available in the latest CI build, and I'm hoping to have 0.4.1 released over the next weekend that will also include this. You can pull the binaries from the latest GHA run:

https://github.com/regclient/regclient/actions/runs/1983942840

If you still see issues with those, let me know and we can reopen this.
