### ISSUE TITLE
make broken

### ISSUE THREAD

**Issue by GregLebreton** [regclient/regclient#192]
Hi, build broken cause go problems

### Current Behavior
output: mod/config.go:23:4: this value of t is never used (SA4006)
pkg/template/template.go:52:17: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)
make: *** [Makefile:37 : lint-go] Erreur 1

### Expected Behavior
build successful

### Steps To Reproduce
1. git clone
2. cd regclient
3. make

**Comment by sudo-bmitch** [comment]
Thanks, this is a combination of 1.18 changes and 1.16 being deprecated in staticcheck. Should be working now.
