### ISSUE TITLE
[Issue] Bash completion is broken using docker argument `--tty`

### ISSUE THREAD

**Issue by git-developer** [regclient/regclient#201]
### Current Behavior
The documentation [suggests](https://github.com/regclient/regclient#running-as-a-container) using the docker arguments `-it` when running `regctl` as a container. This causes the generated bash completion script to be broken.

The behavior is unexpected for users and hard to debug.

### Expected Behavior
1. The documentation should not suggest using the arguments `-it`, at least not for the completion part.
1. The documentation should contain a warning about using `--tty` in combination with `completion`.

The root `README.md` and several other markdown files are affected.

### Steps To Reproduce
```shell
$ source <(docker container run -it --rm regclient/regctl completion bash)
: command not found
-bash: /dev/fd/63: line 3: syntax error near unexpected token `$'\r''
'bash: /dev/fd/63: line 3: `__regctl_debug()
```

### Version
```shell
$ docker image inspect regclient/regctl | jq -r '.[0].Config.Labels["org.opencontainers.image.version", "org.opencontainers.image.revision"]'
v0.4.1
4442cd773c348d7d5e6bd2b9a0cb58e2bce81d67
$ regctl version
{
  "VCSRef": "4442cd773c348d7d5e6bd2b9a0cb58e2bce81d67",
  "VCSTag": "v0.4.1"
}
```

### Environment

```shell
$ echo $BASH_VERSION
5.0.17(1)-release
$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Ubuntu 20.04.4 LTS"
```

### Anything else
When docker is run with `--tty`, the default terminal options are applied. This causes insertion of carriage return (`\r`) characters on popular linux distributions:
```shell
$ docker container run --rm -it regclient/regctl completion bash | grep -c $'\r'
288
$ docker container run --rm -i regclient/regctl completion bash | grep -c $'\r'
0
```

The behavior is by design:
* [docker outputs carriage return when using -t option](https://github.com/moby/moby/issues/37366)
* [docker outputs to standard out with added carriage return character](https://github.com/moby/moby/issues/8513)

**Comment by sudo-bmitch** [comment]
Thanks, this one has bit me a couple times, but I didn't want to break `regctl registry login` with an interactive password prompt. I think that's the only case where it's really needed, so I've updated the example script to handle that one-off case.

**Comment by sudo-bmitch** [comment]
Thanks for keeping me honest on that one!

**Comment by git-developer** [comment]
You're welcome. Thanks for maintaining regclient!
