### ISSUE TITLE
[Feature] Add option to create target repository when using regsync

### ISSUE THREAD

**Issue by kirooshu** [regclient/regclient#203]
### Current Behavior

If the destination (target) repository does not exit, `regsync` gets an error (404 error in the case of ECR) and then `regsync` will loop trying but will never succeed.

### Expected Behavior

In general, for syncing/mirroring tools, creating the destination is an expected default with probably a good option to disable it when the user wants the opposite effect.

### Example Solution

Maybe an option to create the target repository that can also be defined in the `default` section of the `regsync` config file.

**Comment by sudo-bmitch** [comment]
This one sounds like a bug. The code itself should attempt to push even if there's an error checking the target. I'm wondering if it might be related to ECR authentication. Providing the debug logs on this one would help (`regsync once -v debug -c regsync.yml`). Feel free to censor out any hostnames or other sensitive data. Thanks.
