### ISSUE TITLE
[Question] How to login to self-hosted docker registry

### ISSUE THREAD

**Issue by greggameplayer** [regclient/regclient#218]
### Question

Hello, how can i login to self-hosted docker registry ? it keeps trying to use docker hub url with my domain as a directory instead of using my domain directly when i try to do for example "regctl tag ls mydomain"

### Version

0.4.2

### Environment

- Running as binary or container: binary
- Host platform: Windows
- Registry description: registry:2

**Comment by sudo-bmitch** [comment]
Hi @greggameplayer, the `regctl tag ls` works on a repository, not on a registry. So you would run `regctl tag ls myregistry.example.com/path/to/repo`.

For listing repositories on a registry, there's `regctl repo ls myregistry.example.com` that sometimes works, but not all registries support that API for security reasons (in particular, cloud hosted registries that don't want to expose data on different customers tend to not implement that API).

**Comment by sudo-bmitch** [comment]
@greggameplayer you need to include the repo name. E.g. here in my own lab with a registry on `localhost:5000`:

```shell
$ regctl repo ls localhost:5000
library/alpine
library/busybox
library/debian
library/golang
library/nginx
library/node
library/redis
library/registry
library/traefik
library/ubuntu
regclient/regbot
regclient/regctl
regclient/regsync
test

$ regctl tag ls localhost:5000/regclient/regctl
alpine
edge
import
latest
```

**Comment by sudo-bmitch** [comment]
I suspect this one is resolved, but feel free to keep the conversation going here if there are issues or questions with the above.
