### ISSUE TITLE
[Issue] ECR Failed to push blob

### ISSUE THREAD

**Issue by eriksw** [regclient/regclient#221]
### Current Behavior

With regctl 0.4.2, I'm unable to copy from Google Artifact Registry to AWS ECR in China.

It does not appear to be authentication-related because the error appears to be that regctl triggers a 500 after it puts the last chunk.

### Expected Behavior

The copy should succeed like it does when I use 0.3.0.

Copying from Artifact Registry to ECR worked perfectly in 0.3.0 but that version lacks credential helper support, so I'm trying to upgrade so I don't have to deal with the login myself.

I don't want to be stuck with using a very old version of regctl.

### Steps To Reproduce

I have no idea how to reproduce this with public endpoints, but here's a full debug log.

I've made minor format-preserving redactions.

[regctl log.txt](https://github.com/regclient/regclient/files/8682921/regctl.log.txt)

### Version

```text
{
  "VCSRef": "c8125cd51a02bbff6a002f77eb8458b7a7753b63",
  "VCSTag": "v0.4.2"
}
```

### Environment

Source repo: Google Artifact Registry
Destination repo: ECR in AWS China

I'm running regctl cp as a build step in Google Cloud build, using this image and a config that's essentially identical to the examples.

https://github.com/retailnext/docker-copy-step/tree/e09fe017763681738bc653f46bf634a93c8faa64

**Comment by eriksw** [comment]
Here's the log of the same copy succeeding just fine with regctl 0.3.0:

[regctl 0.3.0 log.txt](https://github.com/regclient/regclient/files/8683045/regctl.0.3.0.log.txt)

**Comment by sudo-bmitch** [comment]
It looks like the chunk size has been set to 1048576 (1024*1024) which was the early default. I'm not quite positive how that got into the config, but you should see it in `~/.regctl/config.json`. If you delete that setting so it goes back to the `-1` default, it should work.

**Comment by eriksw** [comment]
There is no `~/.regctl/config.json`. The first and only regctl command ever run was the `regctl copy`.

**Comment by sudo-bmitch** [comment]
@eriksw I still haven't been able to reproduce this one. The 0.4.3 release includes an extra line of debugging that could explain it. When you have a chance, try that version and post a debug log if you still have issues.
