### ISSUE TITLE
[Issue] v0.4.3 regression handling DOCKER_CONFIG environment variable

### ISSUE THREAD

**Issue by nktpro** [regclient/regclient#248]
The [`DOCKER_CONFIG` environment variable](https://docs.docker.com/engine/reference/commandline/cli/#change-the-docker-directory) is commonly used to override the path to the directory that contain the `config.json` file. One important note is that it's the location of the containing directory, not the JSON file itself. For example:

```bash
export DOCKER_CONFIG=/my/custom/.docker
```

Implies the config file is at `/my/custom/.docker/config.json`. 

Prior to `v0.4.3`, this worked perfectly. `regctl` command used to pick up this environment variable as expected.

As of release `v.0.4.3`, this no longer worked. A `regctl image copy ...` command will produce this error:

```
time="..." level=warning msg="Failed to load docker creds" err="read /my/custom/.docker: is a directory"
```

It seems that the changes introduced in https://github.com/regclient/regclient/pull/234 incorrectly treated `DOCKER_CONFIG` as a file path instead of a directory path.

**Comment by sudo-bmitch** [comment]
Woops, thanks for catching that! Let me know if you still see any issues with the latest commit.
