### ISSUE TITLE
[Issue/Support] x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by davidgiga1993** [regclient/regclient#251]
### Background
- I'm using `regclient import` to push an tar image to a registry.
- The registry uses a custom ca
- In total I'm trying to push 2 images (called image A and B) to the same(!) registry.
- Regclient is executed within a gitlab pipeline using a custom docker image
- The docker image contains the correct ca-certificates for our custom ca

### Current Behavior
I can successfully push image A, but the push of image B results in an certificate error.
I also tried using `tls: insecure` but it seems like this isn't used for the authentication part of the request.

```
$ echo "{\"hosts\":{\"${REGISTRY}\":{\"user\":\"unused\",\"pass\":\"$REGISTRY_Q_PASS\",\"tls\":\"insecure\"} }}" > /root/.regctl/config.json
$ regctl -v debug image import "$REGISTRY_Q/image-b:latest" "${CI_PROJECT_DIR}/image-b.tar"
time="2022-06-21T13:47:32Z" level=debug msg="Loading host config" api= blobChunk=0 blobMax=0 hostname=registry.company.com mirrors="[]" name=registry.company.com pathPrefix= repoAuth=false tls=insecure user=unused
time="2022-06-21T13:47:32Z" level=debug msg="regclient initialized"
time="2022-06-21T13:47:32Z" level=debug msg="Image import" file=/builds/image-b.tar ref="registry.company.com/q-auth/image-b:latest"
time="2022-06-21T13:47:32Z" level=debug msg="http req" method=POST url="https://registry.company.com/v2/q-auth/image-b/blobs/uploads/" withAuth=false
time="2022-06-21T13:47:32Z" level=debug msg="Auth request parsed" challenge="[{bearer map[realm:https://registry.company.com/openshift/token]}]"
time="2022-06-21T13:47:32Z" level=debug msg="Auth scope added" host=registry.company.com scope="repository:q-auth/image-b:pull,push"
time="2022-06-21T13:47:32Z" level=debug msg="Failed to generate auth" authtype=bearer err="Post \"https://registry.company.com/openshift/token\": x509: certificate signed by unknown authority" host=registry.company.com
time="2022-06-21T13:47:32Z" level=warning msg="Sleeping for backoff" Host=registry.company.com Seconds=1.99999548
time="2022-06-21T13:47:34Z" level=debug msg="Failed to generate auth" authtype=bearer err="Post \"https://registry.company.com/openshift/token\": x509: certificate signed by unknown authority" host=registry.company.com
time="2022-06-21T13:47:34Z" level=warning msg="Sleeping for backoff" Host=registry.company.com Seconds=3.99999444
time="2022-06-21T13:47:39Z" level=debug msg="Failed to generate auth" authtype=bearer err="Post \"https://registry.company.com/openshift/token\": x509: certificate signed by unknown authority" host=registry.company.com
failed to import layers from docker tar: failed to send blob post, ref registry.company.com/q-auth/image-b:latest: Post "https://registry.company.com/openshift/token": x509: certificate signed by unknown authority
```

### Expected Behavior
This is the result when importing image a (to the same registry)
```
$ echo "{\"hosts\":{\"${REGISTRY}\":{\"user\":\"unused\",\"pass\":\"$REGISTRY_Q_PASS\",\"tls\":\"insecure\"} }}" > /root/.regctl/config.json
$ regctl -v debug image import "$REGISTRY_Q/image-a:latest" "${CI_PROJECT_DIR}/image-a.tar"
time="2022-06-21T11:16:12Z" level=debug msg="Loading host config" api= blobChunk=0 blobMax=0 hostname=registry.company.com mirrors="[]" name=registry.company.com pathPrefix= repoAuth=false tls=insecure user=unused
time="2022-06-21T11:16:12Z" level=debug msg="regclient initialized"
time="2022-06-21T11:16:12Z" level=debug msg="Image import" file=/builds/image-a.tar ref="registry.company.com/q-auth/image-a:latest"
time="2022-06-21T11:16:12Z" level=debug msg="http req" method=POST url="https://registry.company.com/v2/q-auth/image-a/blobs/uploads/" withAuth=false
time="2022-06-21T11:16:12Z" level=debug msg="Auth request parsed" challenge="[{bearer map[realm:https://registry.company.com/openshift/token]}]"
time="2022-06-21T11:16:12Z" level=debug msg="Auth scope added" host=registry.company.com scope="repository:q-auth/image-a:pull,push"
time="2022-06-21T11:16:12Z" level=debug msg="http req" method=POST url="https://registry.company.com/v2/q-auth/image-a/blobs/uploads/" withAuth=true
time="2022-06-21T11:16:13Z" level=debug msg="Upload location received" location="https://registry.company.com/v2/q-auth/image-a/blobs/uploads/9ce54ebc-f406-4e4d-91e7-2b413da60c02?_state=TfQbe8hxtBQmvqRayNgid3mk7vDm5aD17zftrQFZ0_J7Ik5hbWUiOiJpZWMtcS1hdXRoL3RjLXByb3h5LWJhY2tlbmQiLCJVVUlEIjoiOWNlNTRlYmMtZjQwNi00ZTRkLTkxZTctMmI0MTNkYTYwYzAyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIyLTA2LTIxVDExOjE2OjEzLjA2Nzg5OTIwNloifQ%3D%3D"
```

### Version

```text
 regctl version
{
  "VCSRef": "54d930f08ffe16fe817a0de14c17064d9f1c3dee-dirty",
  "VCSTag": ""
}
```
but I also tried an older version

### Environment
- Running inside (custom) container as gitlab pipeline
- Registry: Openshift
- Platform: Linux
- tar file for import generated by kaniko

### Anything else
I've tried running exactly the same container used by the pipeline with the exact same commands with the same tar file and I was able to push image A and B.

Therefore it looks like this isn't a hard issue with regclient but I don't know what else could cause that issue, especially since image A can be pushed in the same pipeline.

@Argannor also took a look at this issue, but we're out of ideas at this point

**Comment by davidgiga1993** [comment]
As a quick test I've added 
```go
if os.Getenv("IGNORE_TLS") == "yes" {
   http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
}
```
and now both images push as expected.

The questions remain:
1) Why does one image work and the other doesn't if the target registry is the same. I would expected both to get a CA error (or none since the environment has a correct cacert)
2) Should regctls `tls: unsecure` also ignore tls for the auth request?

**Comment by sudo-bmitch** [comment]
> The questions remain:
> 
>     1. Why does one image work and the other doesn't if the target registry is the same. I would expected both to get a CA error (or none since the environment has a correct cacert)

I would check that the working image actually requires auth. You'll see that in the debug logs.

>     2. Should regctls `tls: insecure` also ignore tls for the auth request?

It should, and it should work if you inject the TLS cert you want to trust (see `regctl registry set --cacert ...`). That should be the part fixed in #253.

**Comment by davidgiga1993** [comment]
See logs above :) Both require auth

The `:edge` release is completely broken, auth doesn't work anymore at all (for both images, but no tls error):
```
time="2022-06-23T07:38:07Z" level=debug msg="Image import" file=/builds/tc-sb/iec-tc-auth-proxy/frontend.tar ref="registry.company.com/q-auth/image-a:latest"
time="2022-06-23T07:38:07Z" level=debug msg="http req" method=POST url="https://registry.company.com/v2/q-auth/image-a/blobs/uploads/" withAuth=false
time="2022-06-23T07:38:07Z" level=debug msg="Auth request parsed" challenge="[{bearer map[realm:https://registry.company.com/openshift/token]}]"
time="2022-06-23T07:38:07Z" level=debug msg="Auth scope added" host=registry.company.com scope="repository:q-auth/image-a:pull,push"
time="2022-06-23T07:38:07Z" level=debug msg="http req" method=POST url="https://registry.company.com/v2/q-auth/image-a/blobs/uploads/" withAuth=true
time="2022-06-23T07:38:07Z" level=debug msg="Auth request parsed" challenge="[{basic map[error:access denied realm:openshift]}]"
time="2022-06-23T07:38:07Z" level=debug msg="Failed to generate auth" authtype=basic err="no credentials available for basic auth" host=registry.company.com
time="2022-06-23T07:38:07Z" level=debug msg="http req" method=POST url="https://registry.company.com/v2/q-auth/image-a/blobs/uploads/" withAuth=true
time="2022-06-23T07:38:07Z" level=debug msg="Auth request parsed" challenge="[{basic map[error:access denied realm:openshift]}]"
time="2022-06-23T07:38:07Z" level=warning msg="Failed to handle auth request" Err=unauthorized URL="https://registry.company.com/v2/q-auth/image-a/blobs/uploads/"
failed to import layers from docker tar: failed to send blob post, ref registry.company.com/q-auth/image-a:latest: unauthorized
```

**Comment by sudo-bmitch** [comment]
> See logs above :) Both require auth

Oh, I thought that was a mocked up response you wanted. That's a head scratcher. Only thing I can think is some other path was hit that initialized the http client for that host, but I'm not seeing it the logs.

> The `:edge` release is completely broken, auth doesn't work anymore at all (for both images, but no tls error):
> ...
> ```
> msg="Failed to generate auth" authtype=basic err="no credentials available for basic auth" host=registry.company.com
> ```

It doesn't look like you have credentials set inside that container. There are a few options, one is to mount a volume and do the login inside the container:

```
docker container run -it --rm --net host \
  -v regctl-conf:/home/appuser/.regctl/ \
  regclient/regctl:edge registry login registry.company.com
```

and then do your copy with:

```
docker container run -i --rm --net host \
  -v regctl-conf:/home/appuser/.regctl/ \
  -v "${CI_PROJECT_DIR}:${CI_PROJECT_DIR}" \
  regclient/regctl:edge \
    image import "$REGISTRY_Q/image-b:latest" "${CI_PROJECT_DIR}/image-b.tar"
```

Or option B is to use the logins from the host (like `~/.docker/config.json`). You can mount those and run as a user with access to them with:

```
docker container run -i --rm --net host \
  -u "$(id -u):$(id -g)" -e HOME -v $HOME:$HOME \
  -v "${CI_PROJECT_DIR}:${CI_PROJECT_DIR}" \
  regclient/regctl:edge \
    image import "$REGISTRY_Q/image-b:latest" "${CI_PROJECT_DIR}/image-b.tar"
```

For option C, the binaries are available to run outside of a container from GHA: https://github.com/regclient/regclient/actions/runs/2544304728. (Or checkout main and build locally.)

**Comment by davidgiga1993** [comment]
> Oh, I thought that was a mocked up response you wanted. That's a head scratcher. Only thing I can think is some other path was hit that initialized the http client for that host, but I'm not seeing it the logs.

Yes that was the actual log, just anonymized

> It doesn't look like you have credentials set inside that container. There are a few options, one is to mount a volume and do the login inside the container

I copied the binary from the `:edge` image into our pipeline image, nothing else changed. Regctl also prints the registry credentials when doing a `regctl registry config`
