### ISSUE TITLE
[Question] On a registry -> registry sync, possible to skip on error?

### ISSUE THREAD

**Issue by causalityloop** [regclient/regclient#263]
### Question

I have a source registry that has a number of corrupted images (when pulled). When copying the source registry to a target registry (one time mirror), is it possible to skip any pull failures on the source and continue on? Ideally, on the copy, I am looking to discard/leave the source registry behind (along with any broken images/manifests) and move forward/promote the target registry (data set will only include those images/manifests that were successfully copied)

**Comment by sudo-bmitch** [comment]
For a one-off like this, it's probably easiest to do it as a shell script:

```shell
src=reg-a.example.org
tgt=reg-b.example.org
for repo in $(regctl repo ls ${src}); do
  for tag in $(regctl tag ls "${src}/${repo}"); do
    echo "copying ${src}/${repo}:${tag}"
    regctl image copy "${src}/${repo}:${tag}" "${tgt}/${repo}:${tag}"
  done
done
```

That's from memory, so hopefully no syntax errors in there.

**Comment by causalityloop** [comment]
good deal ;) thank you for the sample and thank you for the quick reply.
