### ISSUE TITLE
[Issue] http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by zhangguanzhang** [regclient/regclient#268]
### Current Behavior

```
$ regctl manifest get 10.xxx.xx.xxx:5000/xxx/xxxx
WARN[0000] Sleeping for backoff                          Host="10.xxx.xx.xxx:5000" Seconds=1.9999978120000002
WARN[0002] Sleeping for backoff                          Host="10.xxx.xx.xxx:5000" Seconds=3.999990877
failed to get manifest 10.xxx.xx.xxx:5000/xxx/xxxx:latest: Get "https://10.xxx.xx.xxx:5000/v2/xxx/xxxx/manifests/latest": http: server gave HTTP response to HTTPS client
```

### Steps To Reproduce

1. up a registry:2.7 container,  https://github.com/zhangguanzhang/docker-compose/blob/master/registry/docker-compose.yml
2. Run `regctl manifest get 10.xxx.xx.xxx:5000/xxx/xxxx`
3. See error...
-->

### Version

```text
{
  "VCSRef": "333c44dcfc3b062776ef70a9264ff30914d4770e",
  "VCSTag": "v0.4.4"
}

```

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

**Comment by sudo-bmitch** [comment]
To disable TLS for a registry, run:

```
regctl registry set --tls disabled 10.xxx.xx.xxx:5000
```

**Comment by luvarqpp** [comment]
Note, this would be nice, if stated in readme on first page, where the feature "Self signed, insecure, and http-only registries are all supported." resides. Or at least as available parameter when `regctl --help` is started.

**Comment by sudo-bmitch** [comment]
I've pushed #285 to improve the messaging.
