### ISSUE TITLE
[Feature] non-regex version of tags support in regsync config

### ISSUE THREAD

**Issue by mwgamble** [regclient/regclient#270]
### Current Behavior

In the regsync configuration, the only supported approach for specifying individual tags is with regular expressions.

### Expected Behavior

I would like the ability to supply tags in a form that aren't expected to be regular expressions. I'm accepting (trusted) user input for these values, and don't want to provide them with the flexibility of regular expressions.

### Example Solution

Perhaps `tags` could be just an array of strings, and the full power of regular expressions is only provided if you supply it as a dictionary.

**Comment by sudo-bmitch** [comment]
Hi @mwgamble, to copy a single tag, use the `type: image` setting, e.g.:

```yaml
sync:
  - source: busybox:latest
    target: registry:5000/library/busybox:latest
    type: image
```

And you can take advantage of yaml's support for json to do that in a single line:

```yaml
sync:
  - { type: "image", source: "busybox:latest", target: "registry:5000/library/busybox:latest" }
```

**Comment by mwgamble** [comment]
@sudo-bmitch I didn't realise I could specify tags directly in the `source` and `target` fields. That's great, thankyou!

I have one question: Does the tag in the `target` field have to match the tag in the `source` field?

**Comment by sudo-bmitch** [comment]
The source and target repo and tag can be different. The "image" type is the same as `regctl image copy $src $tgt`.

**Comment by mwgamble** [comment]
Amazing! Thank you so much for this incredible piece of software :heart:
