### ISSUE TITLE
[Question] How to list paginated image tags from quay.io

### ISSUE THREAD

**Issue by davidecavestro** [regclient/regclient#272]
### Question
Does the  _--last_ param work for quay.io?

I've not found a way to obtain other than the 1st 50 tags on quay.io.
i.e. if I get tags for _calico/node_ image from dockerhub I get a lot of tags

```
/tmp$ regctl tag ls calico/node | wc -l
8225
```
but when it comes to quay.io it seems to return just the first 50 tags
I thought the _--last_ param would do the trick, but unless I'm using it the wrong way, it seems not working for quay, as I get the very same contents as when invoked without that flag

```
/tmp$ regctl tag ls quay.io/calico/node | wc -l
50
/tmp$ regctl tag ls quay.io/calico/node | tail -n 3
v3.4.0-0.dev-27-g319e739-ppc64le
v3.4.0-0.dev-28-g909229b-amd64
v3.4.0-0.dev-28-g909229b-arm64
/tmp$ regctl tag ls quay.io/calico/node --last 'v3.4.0-0.dev-28-g909229b-arm64' | tail -n 3
v3.4.0-0.dev-27-g319e739-ppc64le
v3.4.0-0.dev-28-g909229b-amd64
v3.4.0-0.dev-28-g909229b-arm64
```

### Version

```text
{
  "VCSRef": "333c44dcfc3b062776ef70a9264ff30914d4770e",
  "VCSTag": "v0.4.4"
}
```

### Environment

- Running as binary or container: downloaded binary
- Host platform: Linux x86_64
- Registry description: quay.io

### Anything else

I asked the same some days ago on stackoverflow at https://stackoverflow.com/questions/73120440/how-to-list-paginated-image-tags-from-quay-io-using-regctl

**Comment by sudo-bmitch** [comment]
Quay.io seems to be doing some weird stuff with the response:

```
$ regctl tag ls quay.io/calico/node --last v3.4.0-0.dev-28-g909229b-amd64 --limit 5
v3.3.0-2-g441d7c2-arm64
v3.4.0-0.dev-25-g17db8bd
v3.4.0-0.dev-25-g17db8bd-amd64
v3.4.0-0.dev-25-g17db8bd-arm64
v3.4.0-0.dev-25-g17db8bd-ppc64le
```

It should just show the last two images if the repo only has 50 images (which it doesn't), but it returns 5 entries, adding more entries to the start of the list until it gets 5 responses. As best I can tell, their tag API only supports 50 tags no matter the query passed. And it's including the `last` tag rather than showing the tags after last when the limit isn't reached:

```
$ regctl tag ls quay.io/calico/node --last v3.4.0-0.dev-28-g909229b-amd64 --limit 2
v3.4.0-0.dev-25-g17db8bd-amd64
v3.4.0-0.dev-25-g17db8bd-arm64
```

For an example of how a registry should respond to that request, see how Hub responds:

```
$ regctl tag ls calico/node  --limit 10
06d8348
0b3286c-e9613934-1eb2608
2606b97-e0ce0bc-7a66b57
2606b97-e0ce0bca-7a66b57
383a737
43b069c
4d0d1ec
4fac26c-0ff3c42a-f442384
53afe8a
542c040

$ regctl tag ls calico/node  --limit 10 --last 542c040
684ef2b
6889069
69c3089
6ce4f0a
714dda5-36dc8f6f-aa95469
714dda5-48a4a83d-aa95469
714dda5-6af11396-aa95469
765dc25
91d54c3
9512289
```

**Comment by sudo-bmitch** [comment]
Quay appears to track all of their issues in [Jira](https://issues.jboss.org/projects/PROJQUAY). I'm going to close this since it's not really a regclient bug, we're just passing through the response to the OCI API call. But I've also sent a ping over to a few Quay people to see if they have any more details, and I'm happy for the conversation to continue here.

**Comment by davidecavestro** [comment]
Going further I suspect quay/openshift implementation of registry rest api simply decided to somewhat follow the specs diverging from docker reference implementation.
Issuing some CURL commands, you can see that their _link_ response header has - among others - a _next_page_ query param
Using the value from _link_ param for the subsequent call you get the next page
i.e. you would end up with a sequence of calls similar to
```
curl -v 'https://quay.io/v2/calico/node/tags/list?n=20' 
curl -v 'https://quay.io/v2/calico/node/tags/list?n=20&next_page=gAAAAABi5EIwY08OcYRym5Ujrslpl_v7l8EM_jRDvSRYkkqDxpiKTHI9HZpwQQy3vaxj0zZyJlj-efZ4LD06-Or7GI4NaTaClqjDhE_VhjestPyUOxFkMog%3D'
curl -v 'https://quay.io/v2/calico/node/tags/list?n=20&next_page=gAAAAABi5EJMAT3fXZrIRHuUTsFXVhnTuA5eFXwdbO6dlTSuKDXBXUgCveyACCVN_RYFKiNoGLlqyGK_Rg-fKkC-Vg9xnZzS8a98aZoG0eYhCEFe0EVP_0c%3D'

```
where the _next_page_ (actually most of the url) comes from the _link_ header of the previous page's response.
Not sure if it is fully compliant with docker registry v2 specs, but using the _link_ header from previous page's response in a loop could work for most implementations (without sticking to _last_ param implementation detail).

**Comment by sudo-bmitch** [comment]
Interesting that they took that approach since it's not really in the spec (there's one partial mention of the Link header there, but otherwise undefined). I'll work on a tag listing that repeats through link headers until the list ends.

**Comment by sudo-bmitch** [comment]
This should be now supported by #276
