### ISSUE TITLE
[Feature] Homebrew Installation for mac

### ISSUE THREAD

**Issue by Dentrax** [regclient/regclient#280]
### Current Behavior

No installation method for Brew.

### Expected Behavior

To provide better UX for macOS users.

### Example Solution

Create a Homebrew cask and add installation instructions in the README for macOS users.

### Version

`-`

### Environment

- Running as binary or container: `macOS`
- Host platform:
- Registry description:

### Anything else

`-`

**Comment by developer-guy** [comment]
I can take over this one, [goreleaser taps](https://goreleaser.com/customization/homebrew/) might be an option to automate this. WDYT @sudo-bmitch?

**Comment by sudo-bmitch** [comment]
I'd definitely want something automated if this is added. For the most part, the help wanted is because I don't have a Mac to test this. Goreleaser is on the list to research again at some point, so it's worth investigating that for Homebrew too.

**Comment by Akaame** [comment]
@developer-guy @Dentrax Merhaba,

We have been having a discussion with @sudo-bmitch under [this PR](https://github.com/regclient/regclient/pull/415#issuecomment-1518672712). Could you please check the discussion there out and share your feedback?

**Comment by Dentrax** [comment]
Is there any thing we can help with to move forward this one?

**Comment by Moulick** [comment]
Seems to be done by @andyli in https://github.com/Homebrew/homebrew-core/pull/153571
