### ISSUE TITLE
[Feature] Docker plugin regctl with binary file

### ISSUE THREAD

**Issue by pistej** [regclient/regclient#293]
### Current Behavior

Docker regctl plugin command run as docker image. We are using regctl plugin in ours gitlab runners, but gitlab runners have some image cleanup policy and after some time all images are cleaned and when we use regctl command again, new docker images is pulled again.

### Example Solution

I wolud propese add optipon (in makefile) to instal regctl docker plugin with binary file instead of docker image.

### Version

latest

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

**Comment by sudo-bmitch** [comment]
Hi @pistej. If the regctl binary is installed locally, and in your path, the plugin uses this:

https://github.com/regclient/regclient/blob/main/docker-plugin/docker-regclient#L20

The downside of the docker CLI plugin is that Docker is deprecating that feature, so you're better off installing and running the binary directly.

For Gitlab, I believe that using the `regclient/regctl:alpine` image for that particular build step is also a good option.

**Comment by pistej** [comment]
Hi, thanx for quick answer, and pointing out deprecation, ...now I see If condition, thx, will use binary directly.
