### ISSUE TITLE
[Question] Copy image for cartain platforms

### ISSUE THREAD

**Issue by pistej** [regclient/regclient#294]
Hi, is there option to copy image between registers (image layers) only for defined platforms? 
Like `regctl image copy --platform linux/amd64,linux/arm64 <src_image_ref> <dst_image_ref>`

Or another way how to do that? Trying to avoid copy all platform images if I need only two.

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

**Comment by sudo-bmitch** [comment]
It's currently undocumented while I get an environment too test it, since most registries reject an incomplete manifest list. That flag is `--platforms` (plural), e.g.:

```shell
regctl image copy \
  --platforms linux/amd64 --platforms linux/arm64 \
  <src_image_ref> <dst_image_ref>
```

This doesn't mutate the manifest list, so there will be references to platforms that don't exist. To mutate the image, there's `regctl image mod`, and to create a manifest list with just the parts you want, there's `regctl index create`.

I suspect what you want is an on-the-fly copy and mutate of the manifest list, which isn't there yet, but something I'm considering.

**Comment by mspi92** [comment]
I've worked on a similar topic last week and basically implements:
> I suspect what you want is an on-the-fly copy and mutate of the manifest list, which isn't there yet, but something I'm considering.

The source manifest is stripped of all the platforms which are needed (and in case you only specify one platform) a manifest list is converted into an image manifest.
I verified it working with AWS ECR and another registry:v2 based commercial registry (whereas without rewriting it wasn't working).
Open Todo for this is a proper integration of OCI Images, i started but didn't finish it yet, as my requirement was only to get it working for Docker based images.

I'm open for feedback and discussion, i think platform specific copying would be a great addition to regctl

See https://github.com/regclient/regclient/pull/299

**Comment by sudo-bmitch** [comment]
I'm so sorry for not getting back to this earlier. The draft status on the PR had me overlooking it when I should have given it a lot more attention. I ended up going a slightly different direction, but the result is the same. There's now a `regctl index create` command that builds new manifest lists from other references, and I'm merging in a flag to pick multiple platforms from the source. The result looks like:

```
regctl index create \
  --platform linux/amd64 --platform linux/arm64 \
  --ref ${src} ${tgt}
```

If there are any issues getting this to work in your environment, let me know and we can reopen.

**Comment by mosheavni** [comment]
> regctl index create \
>   --platform linux/amd64 --platform linux/arm64 \
>   --ref ${src} ${tgt}

that's what I needed!
just to verify, by doing this I'm copying both the manifest and images? or just the manifest?
Thanks.
