### ISSUE TITLE
[Question] Is regsync resumable?

### ISSUE THREAD

**Issue by peusebiu** [regclient/regclient#295]
### Question

In case blobs/layers are huge, and if there is a pull failure in between, does regsync resumes pulling or starts from scratch?

Thank you!

**Comment by sudo-bmitch** [comment]
During a transfer, regclient has retry logic to attempt to resume a pull or push. For a pull it will fetch from the current progress. For a push, it will fall back to a chunked upload.

This has to be done within the blob copy request, so if regsync is killed, it will restart from the beginning of the blob when the process is restarted. There are also failures that are not recovered, like invalid credentials, and missing data (404). For all the cases where it restarts, it will only copy blobs that are missing on the destination, so if 3/5 blobs were previously pushed, only 2/5 blobs would be copied on the restart.
