### ISSUE TITLE
[Feature] replace version command with provided via kubernetes-sigs/release-utils

### ISSUE THREAD

**Issue by developer-guy** [regclient/regclient#304]
### Current Behavior

When writing this, regctl's version command displays `vcsref` and `vcstag` in JSON by embedding this information into a binary[^1]. I thought we could provide much more information about the build we release.

### Expected Behavior

Alternative way: 
[command.go#L31](https://github.com/kubernetes-sigs/release-utils/blob/main/version/command.go#L31)

### Version

```text
(paste output of `regctl version` or similar for binaries, or `docker image inspect regclient/...` on the image and paste the labels)
```

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

### Anything else

[^1]: https://github.com/regclient/regclient/blob/main/cmd/regctl/root.go#L153

**Comment by developer-guy** [comment]
I'm willing to do this, and [cosign](https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/commands.go#L117) is also using the same method.

**Comment by sudo-bmitch** [comment]
I'm leaning against pulling in a k8s dependency for this, but after 1.18, the embed code can be factored back out. 
https://go.dev/doc/go1.18#debug/buildinfo

I was holding back on this just in case someone was importing from an older version of Go, so I'll have a look at what k8s does for this.
