### ISSUE TITLE
[Issue] Cannot run in a container using local docker creds on Docker for Mac

### ISSUE THREAD

**Issue by Mahoney** [regclient/regclient#307]
### Current Behavior

Running regctl in a container as described here:
https://github.com/regclient/regclient#running-as-a-container

does not work on a Mac using latest Docker for Mac `4.12.0 (85629)` because `/etc/docker/certs.d` does not exist.
### Expected Behavior

It's a documentation problem really - either the docs should stop saying this works "on Linux *and Mac* environments" or (preferably!) they should document how to mount your local docker credentials using Docker for Mac.

(I can't work out how - `~/.docker/config.json` has `"credsStore": "desktop"` which suggests they may be being stored somewhere proprietary?)

### Steps To Reproduce

1. With latest Docker for Mac `4.12.0 (85629)`
2. Login to a docker registry locally using `docker login "$registry"`
3. Run
```bash
 docker container run -i --rm --net host \
  -u "$(id -u):$(id -g)" -e HOME -v $HOME:$HOME \
  -v /etc/docker/certs.d:/etc/docker/certs.d:ro \
  regclient/regctl:latest repo ls "$registry"
```
4. See error...

### Version

```text
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```

### Environment

- Running as binary or container: container
- Host platform: Mac ARM
- Registry description: GHCR

**Comment by sudo-bmitch** [comment]
If that directory doesn't exist on your system, you can skip mounting it:

```
docker container run -i --rm --net host \
  -u "$(id -u):$(id -g)" -e HOME -v $HOME:$HOME \
  regclient/regctl:latest repo ls "$registry"
```

This isn't related to credential helpers. The certs are any custom TLS certificates for private registries.

**Comment by Mahoney** [comment]
Perhaps I've misdiagnosed it, but I still can't login to a registry locally and then interact with it within a container in the way described.

`regctl repo ls ghcr.io` exits with 0 & returns me a long list of repos.

```bash
docker container run -i --rm --net host \
  -u "$(id -u):$(id -g)" -e HOME -v $HOME:$HOME \
  regclient/regctl:latest repo ls ghcr.io
```
exits with 1 and returns me:
```text
time="2022-09-23T09:56:58Z" level=warning msg="Failed to load docker creds" err="Failed to load docker creds error listing credentials - err: exec: \"docker-credential-desktop\": executable file not found in $PATH, out: ``"
Failed to list repositories for ghcr.io: Unauthorized [http 401]
```

**Comment by sudo-bmitch** [comment]
The Alpine based image includes a few credential helpers for AWS and GCR, but not the "desktop" credential helper provided by Docker. The scratch image won't have of these, so you will need to directly login to the registry you want to connect to first, or use the standalone binary. To login (which stores the password in a clear text file):

```
docker container run -it --rm --net host \
  -u "$(id -u):$(id -g)" -e HOME -v $HOME:$HOME \
  regclient/regctl:latest registry login ghcr.io
```

But then you'll find that ghcr, and every other major cloud registry provider, does not permit the `repo ls` API. That would potentially expose private repositories, plus it's way too many repositories to return in the API, so you'll get a permission issue there with any credentials. You should be able to list tags without having any credentials if the repository is public, e.g.:

```
docker container run -i --rm --net host regclient/regctl:latest tag ls ghcr.io/regclient/regctl
```

The volume mount and user in the previous command lets you save registry logins and other settings to `~/.regctl` and it lets you run commands that interact with the local filesystem like `image export` or reading/writing from an `ocidir://...` reference.

**Comment by felipecrs** [comment]
- https://github.com/regclient/regclient/issues/552 may help with this, if you are keen to specify the credentials through CLI flags.

**Comment by sudo-bmitch** [comment]
Closing as I believe this was answered.
