### ISSUE TITLE
[Question] Can I use regctl to do a backup/restore of my registry

### ISSUE THREAD

**Issue by logopk** [regclient/regclient#321]
### Question

Can I use regctl to do a backup/restore of my registry?

My local registry is behaving strangely. garbage-collect deletes more than I would expect. Never mind.

My idea was to export all images (multi-arch and a lot of tags) to file and then start from scratch and import the tars.

Will this work?

I tried this for one image, deleted with garbage-collection, and re-imported.
Docker Registry UI said the manifest was missing.

Before I do all the work of scripting the export, I'd like to make sure this is a valid process.

### Version

```
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```

### Environment

- Running as container
- Your platform: Linux/Debian
- Your registry: registry:2

### Anything else

Thank You for your help.

Peter

**Comment by sudo-bmitch** [comment]
I'm pretty sure the images you're looking for are gone and regclient can't restore them from your registry, but it can copy them from an upstream source. If it's the issue I'm thinking of, the registry:2 image from distribution/distribution has a problem where the child manifests from a multi platform images are not considered tagged:

https://github.com/distribution/distribution/issues/3178

One of these days I'd like to completely rewrite the garbage collection in that project and see if they'll accept a PR.

To answer your question in the title, regclient/regsync is my recommended way to copy lots of images, and even retain backups when an existing tag is going to be overwritten.

**Comment by sudo-bmitch** [comment]
If you try to repair an image that was damaged, by GC or deleting a blob, or any other partial removal, use `--force-recursive`:

```
regctl image copy --force-recursive $src $tgt
```

**Comment by logopk** [comment]
@sudo-bmitch I see.

The images are not destroyed yet. I had to restore a disk backup a couple of times, but now I see that will not be fixed by a backup/restore, as multi_arch is THE root cause.

**Hope you get to fix this and you will get big kudos for this!** 

my multi_arch images are build, tagged  and pushed with docker buildx. All reside in  the same path localhost:5000/logopk/app:v1.x.x (amd64,arm64, armvf)  and :latest

so I don't see how a tag with the architecture would solve the problem....

**Comment by sudo-bmitch** [comment]
> my multi_arch images are build, tagged  and pushed with docker buildx. All reside in  the same path localhost:5000/logopk/app:v1.x.x (amd64,arm64, armvf)  and :latest
> 
> so I don't see how a tag with the architecture would solve the problem....

A multiplatform image has a manifest for the list of platforms, and a manifest for each individual platform. The v1.x.x tag points to that top level multiplatform manifest. The workaround is to create a tag for each of the individual platform manifests. With the digest for a platform manifest, you can create that tag with:

```
regctl image copy \
   localhost:5000/logopk/app@sha256... \
   localhost:5000/logopk/app:v1.x.x-linux-amd64
```

You can get each of those digests in the output of:

```
regctl manifest get localhost:5000/logopk/app:v1.x.x
```

With a bit of work, that could be turned into a shell script to loop over the contents of a repo.

**Comment by logopk** [comment]
I have scripted this and it has worked well - I got my registry down to a 6th of the size after garbage-collection.

Nice that regctl image copy will skip existing digests...

**Comment by logopk** [comment]
For an idea how this works:

- get images 
- iterate over images
- get tags of image
- iterate over tags
- get manifest of tag
- need to copy to new tag if it has a more than one platform
- get the src_image_ref for each platform
- regctl image copy src_image_ref to tag with platform (eg: latest-amd64)
