### ISSUE TITLE
[Feature] configurable parallelism for regsync

### ISSUE THREAD

**Issue by colstrom** [regclient/regclient#328]
### Current Behavior

Currently `regsync` supports a `parallel` option for **copy** operations, but not for **check** operations. In my case, I have >500 images being synced, and the parallel request volume causes my (private, internal, unscaled) registry to return errors. Chunking the config up into smaller segments is a workaround for this that does resolve the issue, but it would be very nice to have a way to override this.

### Expected Behavior

A `parallel_check` option or something of the sort in the config for `regsync` that would limit the number of parallel requests when **checking** if images/manifests need to be synced.

### Example Solution

```yaml
---
defaults:
  parallel_check: 64
  parallel: 8
```

### Version

```json
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```

### Environment

- Running as binary or container: binary
- Host platform: macOS/arm64
- Registry description: `registry:2`

### Anything else

Thank you for making this tool. It has made my life easier, and I appreciate the work that has gone into it.

**Comment by sudo-bmitch** [comment]
I was wondering how long I could get away without limiting that half of the API. Looks like I have the answer. 😄

Thanks for raising the issue. This one should be relatively straight forward to add. I'll take care of it either later this week or over the weekend.

**Comment by colstrom** [comment]
Fantastic, thank you!

**Comment by sudo-bmitch** [comment]
Have a look at #330 for an example to set `reqPerSec` and give that a try. Binaries from CI can be pulled here (or you can use the "edge" images):
 https://github.com/regclient/regclient/actions/runs/3342303518

**Comment by sudo-bmitch** [comment]
Also, if you have details on the errors you were getting from the registry, let me know since there's automatic backoff/retry logic that kicks in for known recoverable issues. An http status code and/or logs from regsync would be helpful (debug would be ideal but I get if you don't want to gather those with 500+ sync commands).

**Comment by colstrom** [comment]
My apologies for the delayed response.

The status codes in the errors were HTTP 400.

Setting the `reqPerSec` option in the config didn't seem to resolve the issue or change the behaviour in any noticeable way, using the CI binaries linked.

Possibly related to this, it seems like when it gets those errors, it behaves as if the image doesn't exist, and needs to be synced (even if it doesn't).

I'll collect some logs the next time I encounter this, which I'd estimate to be sometime in the next week or so.

**Comment by colstrom** [comment]
I found a log line I had shared with a teammate in a chat log, and redacted the image/registry specifics:

```
# ERRO[2022-11-01T11:31:07-07:00] Failed to copy image                          error="failed to send blob post, ref REGISTRY.HOSTNAME/NAMESPACE/IMAGE@sha256:DIGEST: request failed: unexpected http status code: Bad Request [http 400]: <html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n</body>\r\n</html>\r\n" source="STAGING-REGISTRY.HOSTNAME/NAMESPACE/IMAGE:TAG" target="REGISTRY.HOSTNAME/NAMESPACE/IMAGE:TAG"
```

Thats exactly the sort of error I see when this occurs.

Hope that helps!

**Comment by sudo-bmitch** [comment]
The `reqPerSec` can also be a decimal to further throttle it, e.g.

```
reqPerSec: 0.5
```

To limit to one request every 2 seconds. You should definitely notice it slow down when you do that.

If the issue is concurrent requests, rather than frequent requests, make sure to also set something like:

```
reqConcurrent: 10
```

Which will limit the number of simultaneous connections.

I'll dig into the 400 error code. I don't think that's typically a recoverable error. But maybe there are some exceptions.

**Comment by sudo-bmitch** [comment]
Checking through the spec, all of the 400 responses are fatal errors that shouldn't be retried. Hopefully the `reqConcurrent` setting helps with the issues you've seen.
