### ISSUE TITLE
unable to reuse reader

### ISSUE THREAD

**Issue by drev74** [regclient/regclient#331]
### Current Behavior

I was able to copy an `alpine` image with : `regctl image copy alpine xxxhost/alpine`

Failed to copy a grafana image to the registry running the latest `registry:2` with 
`regctl image copy grafana/grafana-oss:9.2.2 xxxhost/grafana/grafana-oss:9.2.2`

### Expected Behavior

Seamlessly copy an image with the `latest` or particular tag to my private registry

### Steps To Reproduce

Works ---> `regctl image copy alpine xxxhost/alpine`

Fails   ---> `regctl image copy grafana/grafana-oss xxxhost/grafana/grafana-oss`
Fails   ---> `regctl image copy grafana/grafana-oss:9.2.2 xxxhost/grafana/grafana-oss:9.2.2`

### Version
```text
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```
### Environment

Registry: VM instance with an external reverse proxy with HTTPS termination
registry:2 is running as a plain HTTP on the VM instance

- Running as binary or container: binary release v0.4.5
- Host platform: Ubuntu 21.04
- Registry description: the latest `registry:2`

### Anything else

> regctl image copy grafana/grafana-oss:9.2.2 xxxhost/grafana/grafana-oss:9.2.2 -v info    
INFO[0002] Copy not needed, target already up to date    digest="sha256:b789c063ceb1adc122b392641a32c688283f7b37d906acbf229daca76a7fa8c3" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0002] Copy not needed, target already up to date    digest="sha256:e3f2274f1b6c7b4679117dff40f0907b9480361b4be95680c4460e0ec2d185c7" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0003] Copy config                                   digest="sha256:c87a064999ddd1321820d2d3165c374e40af71c7c1fba66756e910f1e509350a" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0003] Copy layer                                    layer="sha256:59775c20a906b1a49edcdc41a700a795998979d6ecf8f8d9cd7cbdf45e686d81" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0003] Copy layer                                    layer="sha256:157ca9904b40d5953000d1685887e5781a50d869d0dd6e2cdaf35d702ec0e59e" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0003] Copy layer                                    layer="sha256:a0ea00a1d83b79455c4818eced3ead2d06e93f01f3640dcd309ec3525dbca6a0" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0003] Copy layer                                    layer="sha256:81bd6880165a34b52adfdc158a5564c534278066d0280c506a74ed3acdfca856" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0003] Copy layer                                    layer="sha256:78d9b9e0a368112ae43c3041d733e4fce8df274ebc64917b107ddbfcd4187673" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0003] Copy layer                                    layer="sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
WARN[0034] Sleeping for backoff                          Host=xxxhost Seconds=1.999998363
WARN[0036] Failed to push blob                           err="failed to send blob (put), digest sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df, ref xxxhost/grafana/grafana-oss@sha256:e5ae3b0b14c161a2d1f39f5fc0b8527870ed21c99b096f51daf52439b9d98b63: unable to reuse reader" src="grafana/grafana-oss:9.2.2" tgt="xxxhost/grafana/grafana-oss:9.2.2"
WARN[0036] Failed to copy layer                          err="failed to send blob (put), digest sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df, ref xxxhost/grafana/grafana-oss@sha256:e5ae3b0b14c161a2d1f39f5fc0b8527870ed21c99b096f51daf52439b9d98b63: unable to reuse reader" layer="sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
failed to send blob (put), digest sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df, ref xxxhost/grafana/grafana-oss@sha256:e5ae3b0b14c161a2d1f39f5fc0b8527870ed21c99b096f51daf52439b9d98b63: unable to reuse reader

**Comment by drev74** [comment]
Built a binary from master. Result is the same:
```bash
VCSRef:     e5b53340c4e4d4ca8dc799e06ec057513b89a448
VCSCommit:  e5b53340c4e4d4ca8dc799e06ec057513b89a448
VCSState:   clean
VCSDate:    2022-10-28T02:17:43Z
Platform:   linux/amd64
GoVer:      go1.19.2
GoCompiler: gc
```

**Comment by sudo-bmitch** [comment]
The "unable to reuse reader" is a secondary error after something broke the initial copy. It's a sign that I need to cleanup how error messages get propagated when there are retries, and figure out why the blob reader isn't resetting. To find the cause, try using `-v debug` to get more details.

**Comment by drev74** [comment]
Below is the debug output (trimmed to last few successful ops):
```bash
INFO[0004] Copy layer                                    layer="sha256:78d9b9e0a368112ae43c3041d733e4fce8df274ebc64917b107ddbfcd4187673" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
DEBU[0004] http req                                      method=HEAD url="https://xxxhost/v2/grafana/grafana-oss/blobs/sha256:78d9b9e0a368112ae43c3041d733e4fce8df274ebc64917b107ddbfcd4187673" withAuth=true
DEBU[0004] Blob copy skipped, already exists             digest="{application/vnd.docker.image.rootfs.diff.tar.gzip 92 sha256:78d9b9e0a368112ae43c3041d733e4fce8df274ebc64917b107ddbfcd4187673 [] map[] [] <nil> }" tgt="xxxhost/grafana/grafana-oss:9.2.2"
INFO[0004] Copy layer                                    layer="sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
DEBU[0004] http req                                      method=HEAD url="https://xxxhost/v2/grafana/grafana-oss/blobs/sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" withAuth=true
DEBU[0004] Request failed                                Status="Not Found" URL="https://xxxhost/v2/grafana/grafana-oss/blobs/sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df"
DEBU[0004] http req                                      method=GET url="https://registry-1.docker.io/v2/grafana/grafana-oss/blobs/sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" withAuth=true
DEBU[0004] http req                                      method=POST url="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/?mount=sha256%3A3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" withAuth=true
DEBU[0004] http req                                      method=PUT url="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/1b56b456-86f6-401f-9211-da794c7dc07b?_state=ejQfqTFF9NM9lwN5IOWNTU8QCRCd-LyF1LPZj45iJ157Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjFiNTZiNDU2LTg2ZjYtNDAxZi05MjExLWRhNzk0YzdkYzA3YiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMC0zMFQwODo1OTozMy41NTU0OTc3MjJaIn0%3D&digest=sha256%3A3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" withAuth=true

WARN[0034] Sleeping for backoff                          Host=xxxhost Seconds=1.999995974
WARN[0036] Failed to push blob                           err="failed to send blob (put), digest sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df, ref xxxhost/grafana/grafana-oss@sha256:e5ae3b0b14c161a2d1f39f5fc0b8527870ed21c99b096f51daf52439b9d98b63: unable to reuse reader" src="grafana/grafana-oss:9.2.2" tgt="xxxhost/grafana/grafana-oss:9.2.2"
WARN[0036] Failed to copy layer                          err="failed to send blob (put), digest sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df, ref xxxhost/grafana/grafana-oss@sha256:e5ae3b0b14c161a2d1f39f5fc0b8527870ed21c99b096f51daf52439b9d98b63: unable to reuse reader" layer="sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df" source="grafana/grafana-oss:9.2.2" target="xxxhost/grafana/grafana-oss:9.2.2"
failed to send blob (put), digest sha256:3252608fd70d63011112a874af64b1fe1031f316379fba394e119185b49f92df, ref xxxhost/grafana/grafana-oss@sha256:e5ae3b0b14c161a2d1f39f5fc0b8527870ed21c99b096f51daf52439b9d98b63: unable to reuse reader
```

**Comment by sudo-bmitch** [comment]
It looks like it took exactly 30 seconds for that failure, which may indicate a timeout somewhere (possibly the network). I'll work on improving the retry of blob copies between registries, and hopefully better error messages.

Until then, two things to try. If you have access to the registry server logs, check if they give any indication of the issue. And for better retry handling, using an intermediate OCI layout should be able to retry the push since that blob reader can be reset to the start of the local file (an OCI layout is a directory with a structure of files that can be treated like a repository):

```
regctl image copy grafana/grafana-oss:9.2.2 ocidir://grafana-oss:9.2.2 -v info
regctl image copy ocidir://grafana-oss:9.2.2 xxxhost/grafana/grafana-oss:9.2.2 -v info
```

**Comment by drev74** [comment]
Upd: I tried for `registry:2.8.1` and `2.8.0`. The result is the same. Here's the server log from my `registry:2.8.1`

```bash
time="2022-10-30T12:41:54.821395677Z" level=info msg="authorized request" go.version=go1.16.15 http.request.contenttype="application/octet-stream" http.request.host=xxxhost http.request.id=b6d8c15c-803c-432d-90a3-b5c3159eb65b http.request.method=PUT http.request.remoteaddr=X.X.X.X http.request.uri="/v2/grafana/grafana-oss/blobs/uploads/58f39192-9175-4f9f-b071-6426052e0900?_state=bS8ONy8R-Pmlxqvqt7XvpNXeB8ZCu9uzUycF8Ix1VPR7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjU4ZjM5MTkyLTkxNzUtNGY5Zi1iMDcxLTY0MjYwNTJlMDkwMCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMC0zMFQxMjo0MTo1NC43MzA3NDU1MzVaIn0%3D&digest=sha256%3A6bdd5eb5e6357dcd3189b223736d42529f093b5f7b139bd85ea213878f772461" http.request.useragent="regclient/regctl (e5b53340c4e4d4ca8dc799e06ec057513b89a448)" vars.name="grafana/grafana-oss" vars.uuid=58f39192-9175-4f9f-b071-6426052e0900 
time="2022-10-30T12:42:24.81381321Z" level=error msg="client disconnected during blob PUT" auth.user.name=tampler contentLength=97288654 copied=60595514 error="unexpected EOF" go.version=go1.16.15 http.request.contenttype="application/octet-stream" http.request.host=xxxhost http.request.id=b6d8c15c-803c-432d-90a3-b5c3159eb65b http.request.method=PUT http.request.remoteaddr=XXXX http.request.uri="/v2/grafana/grafana-oss/blobs/uploads/58f39192-9175-4f9f-b071-6426052e0900?_state=bS8ONy8R-Pmlxqvqt7XvpNXeB8ZCu9uzUycF8Ix1VPR7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjU4ZjM5MTkyLTkxNzUtNGY5Zi1iMDcxLTY0MjYwNTJlMDkwMCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMC0zMFQxMjo0MTo1NC43MzA3NDU1MzVaIn0%3D&digest=sha256%3A6bdd5eb5e6357dcd3189b223736d42529f093b5f7b139bd85ea213878f772461" http.request.useragent="regclient/regctl (e5b53340c4e4d4ca8dc799e06ec057513b89a448)" vars.name="grafana/grafana-oss" vars.uuid=58f39192-9175-4f9f-b071-6426052e0900 
2022/10/30 12:42:25 http: superfluous response.WriteHeader call from github.com/docker/distribution/vendor/github.com/gorilla/handlers.(*responseLogger).WriteHeader (handlers.go:125)
time="2022-10-30T12:42:25.622268028Z" level=error msg="response completed with error" auth.user.name=tampler err.code=unknown err.detail="client disconnected" err.message="unknown error" go.version=go1.16.15 http.request.contenttype="application/octet-stream" http.request.host=xxxhost http.request.id=b6d8c15c-803c-432d-90a3-b5c3159eb65b http.request.method=PUT http.request.remoteaddr=X.X.X.X http.request.uri="/v2/grafana/grafana-oss/blobs/uploads/58f39192-9175-4f9f-b071-6426052e0900?_state=bS8ONy8R-Pmlxqvqt7XvpNXeB8ZCu9uzUycF8Ix1VPR7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjU4ZjM5MTkyLTkxNzUtNGY5Zi1iMDcxLTY0MjYwNTJlMDkwMCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMC0zMFQxMjo0MTo1NC43MzA3NDU1MzVaIn0%3D&digest=sha256%3A6bdd5eb5e6357dcd3189b223736d42529f093b5f7b139bd85ea213878f772461" http.request.useragent="regclient/regctl (e5b53340c4e4d4ca8dc799e06ec057513b89a448)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=30.808735831s http.response.status=500 http.response.written=89 vars.name="grafana/grafana-oss" vars.uuid=58f39192-9175-4f9f-b071-6426052e0900
```

**Comment by drev74** [comment]
> regctl image copy grafana/grafana-oss:9.2.2 ocidir://grafana-oss:9.2.2 -v info
   regctl image copy ocidir://grafana-oss:9.2.2 xxxhost/grafana/grafana-oss:9.2.2 -v info

This worked with issues. While I was able to copy an image to my private registry and was able to list its name and tags, I was getting this:
```bash
admin@tc:~/ci$ docker pull docker:5000/golang:1.19.2-alpine
1.19.2-alpine: Pulling from golang
manifest for docker:5000/golang:1.19.2-alpine not found: manifest unknown: manifest unknown
```
This shows that the manifest was invalid/absent and  I was NOT able to pull this image.

When I tagged the image locally and pushed to my private registry, things worked smoothly:

// Local tagging on my lap and pushing
```bash
docker tag golang:1.19.2-alpine docker:5000/golang:1.19.2-alpine
docker push docker:5000/golang:1.19.2-alpine
```

// Private repo remote user:
```bash
admin@tc:~/ci$ docker pull docker:5000/golang:1.19.2-alpine
1.19.2-alpine: Pulling from golang
213ec9aee27d: Pull complete 
```

**Comment by sudo-bmitch** [comment]
> `client disconnected during blob PUT`

That's leaning towards something timing out on the network.

> ```
> admin@tc:~/ci$ docker pull docker:5000/golang:1.19.2-alpine
> 1.19.2-alpine: Pulling from golang
> manifest for docker:5000/golang:1.19.2-alpine not found: manifest unknown: manifest unknown
> ```

Show the `regctl image copy` command for this one. It suggests the name you pushed and the name you tried to `docker pull` are not the same.

**Comment by drev74** [comment]
I provided an output from another command, which does the same.
If you want, I can give you a temporary remote access to my private registry to run integration tests for this

**Comment by sudo-bmitch** [comment]
The latest commit to main should help with the issues copying between registries. It won't help with the underlying problem, but hopefully it will retry and fallback to a chunked upload, which can help with difficult networks.

**Comment by drev74** [comment]
Still not working. I rebuilt the latest master with go1.19.3 and got the following:
```bash
// copy image

> regctl image copy grafana/grafana-oss:9.2.3 xxxhost/grafana/grafana-oss:9.2.3 -v debug

DEBU[0047] http req                                      method=GET url="https://registry-1.docker.io/v2/grafana/grafana-oss/blobs/sha256:7968ff9bb24ef[0/273]f587581017ebed7a7e4d1584d99771354fe0752bd053" withAuth=true                                                                                                   DEBU[0047] http req                                      method=PUT url="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/60b7930c-b7ed-4b37-9608-719be8a2710e?_state=cxcGx8C0vRK2qaszvCcF4gvyNvcKxc3AV0_DG4GVMyN7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjYwYjc5MzBjLWI3ZWQtNGIzNy05NjA4LTcxOWJlOGEyNzEwZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMS0wNFQwOToxMzoxOS45MzI2NDE5NzVaIn0%3D&digest=sha256%3A7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053" withAuth=true
DEBU[0048] Request failed                                Status="Not Found" URL="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/60b7930c-b7ed-4b37-9608-719be8a2710e?_state=cxcGx8C0vRK2qaszvCcF4gvyNvcKxc3AV0_DG4GVMyN7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjYwYjc5MzBjLWI3ZWQtNGIzNy05NjA4LTcxOWJlOGEyNzEwZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMS0wNFQwOToxMzoxOS45MzI2NDE5NzVaIn0%3D&digest=sha256%3A7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053"                                                                                                                                     DEBU[0048] http req                                      method=GET url="https://registry-1.docker.io/v2/grafana/grafana-oss/blobs/sha256:7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053" withAuth=true
DEBU[0048] http req                                      method=PATCH url="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/60b7930c-b7ed-4b37-9608-719be8a2710e?_state=cxcGx8C0vRK2qaszvCcF4gvyNvcKxc3AV0_DG4GVMyN7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjYwYjc5MzBjLWI3ZWQtNGIzNy05NjA4LTcxOWJlOGEyNzEwZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMS0wNFQwOToxMzoxOS45MzI2NDE5NzVaIn0%3D&digest=sha256%3A7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053" withAuth=true                                                                                                                             DEBU[0049] Request failed                                Status="Not Found" URL="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/60b7930c-b7ed-4b37-9608-719be8a2710e?_state=cxcGx8C0vRK2qaszvCcF4gvyNvcKxc3AV0_DG4GVMyN7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjYwYjc5MzBjLWI3ZWQtNGIzNy05NjA4LTcxOWJlOGEyNzEwZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMS0wNFQwOToxMzoxOS45MzI2NDE5NzVaIn0%3D&digest=sha256%3A7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053"                                                                                                                                     DEBU[0049] http req                                      method=GET url="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/60b7930c-b7ed-4b37-9608-719be8a2710e?_state=cxcGx8C0vRK2qaszvCcF4gvyNvcKxc3AV0_DG4GVMyN7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjYwYjc5MzBjLWI3ZWQtNGIzNy05NjA4LTcxOWJlOGEyNzEwZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMS0wNFQwOToxMzoxOS45MzI2NDE5NzVaIn0%3D&digest=sha256%3A7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053" withAuth=true
DEBU[0049] Request failed                                Status="Not Found" URL="https://xxxhost/v2/grafana/grafana-oss/blobs/uploads/60b7930c-b7ed-4b37-9608-719be8a2710e?_state=cxcGx8C0vRK2qaszvCcF4gvyNvcKxc3AV0_DG4GVMyN7Ik5hbWUiOiJncmFmYW5hL2dyYWZhbmEtb3NzIiwiVVVJRCI6IjYwYjc5MzBjLWI3ZWQtNGIzNy05NjA4LTcxOWJlOGEyNzEwZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0xMS0wNFQwOToxMzoxOS45MzI2NDE5NzVaIn0%3D&digest=sha256%3A7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053"                                                                                                                                     WARN[0049] Failed to push blob                           err="failed to send blob (chunk), ref xxxhost/grafana/grafana-oss@sha256:7c9c2545f4143b4b5303f88d463fb5276d8524648634c6b7a0579897259ac0ac: http status: not found [http 404]" src="grafana/grafana-oss:9.2.3" tgt="xxxhost/grafana/grafana-oss:9.2.3"                                                                                                                                          WARN[0049] Failed to copy layer                          err="failed to send blob (chunk), ref xxxhost/grafana/grafana-oss@sha256:7c9c2545f4143b4b5303f88d463fb5276d8524648634c6b7a0579897259ac0ac: http status: not found [http 404]" layer="sha256:7968ff9bb24efd978fa6f587581017ebed7a7e4d1584d99771354fe0752bd053" source="grafana/grafana-oss:9.2.3" target="xxxhost/grafana/grafana-oss:9.2.3"                                                    failed to send blob (chunk), ref xxxhost/grafana/grafana-oss@sha256:7c9c2545f4143b4b5303f88d463fb5276d8524648634c6b7a0579897259ac0ac: http status: not found [http 404]                                                                                                                            
```
```bash
// list the private reg

> regctl tag ls xxxhost/grafana/grafana-oss  
failed to list tags for xxxhost/grafana/grafana-oss:latest: request failed: not found [http 404]: {"errors":[{"code":"NAME_UNKNOWN","message":"repository name not known to registry","detail":{"name":"grafana/grafana-oss"}}]}
```

PS: 
1. I was able to copy an alpine image
2. My internet link is the full cable 100Mbps
3. Still can provide you a temp access to my private repo for integration testing

**Comment by sudo-bmitch** [comment]
The 404 on the patch request with distribution/distribution (the upstream of the registry image) means even the patch request is getting dropped by the network. There was a server side fix for this to give a recoverable error message. Try building/running the latest registry image that includes this PR:

https://github.com/distribution/distribution/pull/3755

**Comment by drev74** [comment]
UPD: built the latest master today and tried another container with the latest `registry:2` update

This seems to be a flacky bug. For smaller container sizes (e.g size <= 128Mb), `regctl` works okay and copies images properly.
For larger sizes (e.g > 300Mb), I'm getting the same issues from `regctl`:
```bash
WARN[0037] Sleeping for backoff ...
WARN[0049] Failed to push blob ...
WARN[0049] Failed to copy layer ...
```

**Comment by drev74** [comment]
> The 404 on the patch request with distribution/distribution (the upstream of the registry image) means even the patch request is getting dropped by the network. There was a server side fix for this to give a recoverable error message. Try building/running the latest registry image that includes this PR:
> 
> [distribution/distribution#3755](https://github.com/distribution/distribution/pull/3755)

I'll give it a try for research purposes, but I highly doubt that anyone would patch a critical production infra image with 100M+ downloads just to match the expected functionality of your tool. So that's just not happening in production

**Comment by sudo-bmitch** [comment]
> > The 404 on the patch request with distribution/distribution (the upstream of the registry image) means even the patch request is getting dropped by the network. There was a server side fix for this to give a recoverable error message. Try building/running the latest registry image that includes this PR:
> > 
> > [distribution/distribution#3755](https://github.com/distribution/distribution/pull/3755)
> 
> I'll give it a try for research purposes, but I highly doubt that anyone would patch a critical production infra image with 100M+ downloads just to match the expected functionality of your tool. Not happening

Distribution/distribution merged the change because they weren't following the spec. Docker Hub has already applied that fix. regclient is the only library I've seen that will fall back to a chunked upload with retries when the network drops the connection. All the other tools I've seen just fail immediately or retry the full blob upload. Because of that, it tends to find registry implementation issues in chunked uploads.
