### ISSUE TITLE
[Question] Release 1.0.0

### ISSUE THREAD

**Issue by ddelange** [regclient/regclient#336]
### Question

Hi! 👋 

I've personally happily used your tool, thanks a lot. For a bigger project however, the [objection](https://github.com/PrefectHQ/prefect/issues/5388#issuecomment-1238175822) came up that the tool is not on a stable version yet.

Are there any plans for public API changes in the near future? If no, would it be possible to release 1.0.0?

Many thanks!

**Comment by sudo-bmitch** [comment]
I would consider the `regctl` and `regsync` commands relatively stable at this point, and changes are mainly in the form of new functionality that doesn't impact existing features.

The Go API is still considered under development. Adding the 1.0.0 designation would handcuff the ability to make future changes to the project and rapidly iterate support for specs that are not yet GA upstream. That said, the core methods to list tags, push and pull manifests and blobs, and copy images, are not expected to change. Most of the changes are in features like image mutation and artifact management.

**Comment by ddelange** [comment]
thanks for the quick reply!
