### ISSUE TITLE
[Feature] Timeout for image copy

### ISSUE THREAD

**Issue by MartinEmrich** [regclient/regclient#338]
### Current Behavior

`regctl image copy` sometimes gets stuck while copying to AWS ECR. I don't blame regclient, more probably it's AWS (`strace` shows repeated TEMPORARY UNAVAILABLE on the socket to AWS).

### Expected Behavior

A (configurable) timeout option would be nice.

### Example Solution

`regctl image copy --timeout=300 source/image target/image` would abort if the copy is not finished within 5 minutes

**Comment by sudo-bmitch** [comment]
Hi @MartinEmrich, please include the debug output (`-v debug`) when the image copy is hanging. I need to understand if it's stuck in a retry loop or if this is in the Go http reader/writer.

**Comment by MartinEmrich** [comment]
I have set the option in our script.

But while we use "regctl image copy" for 4 months now, this only happened today, so I guess it might take a long time until it happens again. If it does, I'll report back.
