### ISSUE TITLE
[Feature] reading password from stdin by accepting it via --password-stdin flag

### ISSUE THREAD

**Issue by developer-guy** [regclient/regclient#345]
### Current Behavior

The only way of authenticating to the registry in regctl is passing the password through a flag `--pass` in `registry login` cmd, so we can read `stdin` to accept passwords to increase security by not keeping any passwords in the shell history.

### Expected Behavior

Reading the password from stdin while authenticating to the registry like the following:

```shell
$ pbpaste |& regctl registry login docker.io -u developerguy --password-stdin
```

### Version

```text
 regctl version
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```

### Environment

- Running as binary or container: binary
- Host platform: Mac/x86
- Registry description: 

### Anything else

I'm willing to do this, please assign it to me if you want me to do it.

**Comment by sudo-bmitch** [comment]
@developer-guy great suggestion. I've merged in a change for this. Keep the ideas coming!
