### ISSUE TITLE
Unable to run regctl on Mac

### ISSUE THREAD

**Issue by Bhashkarjya** [regclient/regclient#346]
Hi Team,
I'm trying to install regctl on my M1 Mac.
OS: MacOS Monterey

I tried to install using the following commands:
```
curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-arm64 >regctl
sudo chmod 755 regctl
```
On trying to run **regctl** or **./regctl**, it throws the following error:
`zsh: command not found: regctl`

**Comment by sudo-bmitch** [comment]
Hi @Bhashkarjya. On Mac, you want to pull the Darwin binaries rather than the Linux ones:

```
https://github.com/regclient/regclient/releases/latest/download/regctl-darwin-arm64
```

**Comment by Bhashkarjya** [comment]
./regctl is working now. Thanks for the help.
