### ISSUE TITLE
manually created tars - "unable to export all files from tar: not found"

### ISSUE THREAD

**Issue by somesocks** [regclient/regclient#354]
### Current Behavior

I want to do some manual manipulation of an OCI image before pushing it to a registry, so I have a build script that:
- runs a dockerx build, with an export to a tar
- extracts the OCI image tar to a working directory, and makes some changes
- compresses the OCI image again with tar

After I do this, when I try to run `regctl image import $IMAGE_REGISTRY/$IMAGE_NAME $IMAGE_TAR`, I get `unable to export all files from tar: not found` from regctl.  The original OCI tar uploads fine.

I suspect the issue is related to tar prefixing "./" to the path for entries in the archive when you run `tar -cf $ARCHIVE -C $BASE_DIRECTORY .`, which probably causes the handler lookups in `regclient/image.go` to fail.  I believe this is the issue because when I create the archive with `tar -cf $ARCHIVE -C $BASE_DIRECTORY . --transform='s,^\./,,'`, the tar works again.

I realize this is a bit of an edge case, but I think normalizing the tar paths before matching in `image.go` would probably help avoid weird one-off bugs when image archives are generated by non-docker tools.

### Expected Behavior

I'd expect regclient to handle image tars with the './' path prefix, and maybe do other normalization on tar entries during image imports. 

### Steps To Reproduce

1. create an OCI image tarball using a standard tool.
2. extract the tar into a directory
3. re-archive the tar: `tar -cf <ARCHIVE> -C <OCI_IMAGE_DIR> .`
4. run `regctl image import <IMAGE> <ARCHIVE>`
5. regctl throws error `unable to export all files from tar: not found`

### Version

- tar - GNU tar 1.4
- regctl `{ "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f", "VCSTag": "v0.4.5" }`

### Environment

- linux
- amd64
- registry: the standard docker 2.0 registry image
- regctl running as a binary

**Comment by sudo-bmitch** [comment]
Thanks for the report @somesocks. I need to work on the tests for #355, sort out what recently changed with the upstream linter, and check for other occurrences of this in the code. While I'm doing that, feel free to give those changes a try and let me know if they give you any other trouble.

And if you're modifying the contents, make sure that also includes updating the digests and manifests where those digests are stored. The complication of doing that is a big reason for making the `regctl image mod` command. If there's some new functionality you'd like to see with that tool, feel free to raise a feature request.
