### ISSUE TITLE
[Question] When working with export/import can one control the repository prefix?

### ISSUE THREAD

**Issue by chadlwilson** [regclient/regclient#377]
### Question

When working with local images to load the relevant platform from an OCI image similar to your instructions [here](https://stackoverflow.com/questions/72945407/how-do-i-import-and-run-a-multi-platform-oci-image-in-docker-for-macos) the image ends up loaded locally as `localhost/toy:tag` with the `localhost/` seemingly fixed or implied by the use of an `ocidir://`

Is there a way I'm missing to control the full repository name that end up in the `manifest.json`'s `RepoTags` when loading something locally like this, or make it omit the `localhost/`?

### Version

```text
VCSRef:     f43ada160d953317c51e7d9170afa2a316f4b9be
VCSCommit:  f43ada160d953317c51e7d9170afa2a316f4b9be
VCSState:   clean
VCSDate:    2023-02-26T02:43:41Z
Platform:   darwin/arm64
GoVer:      go1.20.1
GoCompiler: gc
```

### Environment

- Running as binary or container: binary
- Host platform: Mac, arm64
- Registry description: N/A

### Anything else

Yes, I know I can just `docker tag localhost/toy:latest toy:latest` or similar, but fewer commands is cleaner to understand :-)

**Comment by sudo-bmitch** [comment]
Hi @chadlwilson. That's not currently a feature, but it wouldn't hurt to add that as a flag. Of course if you did a `regctl image import $name $file` you would control the name, so this is needed on the `regctl export` to support the `docker load` command.

**Comment by sudo-bmitch** [comment]
@chadlwilson I've added a flag for this in the latest update. To test this there are 3 options:

- Build from main (`go install github.com/regclient/regclient/cmd/regctl@main`)
- Run it as a container (`regclient/regctl:edge`)
- Download the binaries from GHA: https://github.com/regclient/regclient/actions/runs/4309380487

If it gives you any trouble, let me know and we can reopen this. Thanks again for the suggestion and let me know if you see any other missing features.

**Comment by chadlwilson** [comment]
Wow thanks, will try and give it a go some time soon.

**Comment by chadlwilson** [comment]
> Wow thanks, will try and give it a go some time soon.

Gave it a go, and works as expected, thanks!

Couple of thoughts, feel free to ignore at will:
- is `--name` the consistent canonical terminology used for what ends up in `RepoTags` that incorporates the `registry/repository:tag` combination? Will that be clear enough for folks? I can't see such a flag being referred to in [the docs](https://github.com/regclient/regclient/blob/main/docs/regctl.md#image-commands), but perhaps it exists elsewhere - I am newish to `regctl` and friends and have seem different terminology across docker-land.
- For fun, i tried including two `--name` flags to see if it will embed multiple `RepoTags`, but only the last one applies. No big deal. 😉
- Perhaps the `--help` docs might need to mention the default behaviour if you don't specify?

```
Usage:
  regctl image export <image_ref> [filename] [flags]

Flags:
  -h, --help              help for export
      --name string       Name of image to embed for docker load
  -p, --platform string   Specify platform (e.g. linux/amd64 or local)
```

One minor gripe _unrelated_ to `regctl` is that even when using `docker buildx build --dest type=oci,dest=my.tar --tag hello/world:v1.2.0` for a single-platform image, the tag isn't included in the `manifest.json`'s `RepoTags` that is generated either. Sigh. Will try my luck on that one with the buildx folks. 😅

**Comment by sudo-bmitch** [comment]
>     * is `--name` the consistent canonical terminology used for what ends up in `RepoTags` that incorporates the `registry/repository:tag` combination? Will that be clear enough for folks? I can't see such a flag being referred to in [the docs](https://github.com/regclient/regclient/blob/main/docs/regctl.md#image-commands), but perhaps it exists elsewhere - I am newish to `regctl` and friends and have seem different terminology across docker-land.

The canonical term is "reference", but outside of people writing the code, it's a lesser known term. Naming things is hard, so I'll consider other values for the flag.

>     * For fun, i tried including two `--name` flags to see if it will embed multiple `RepoTags`, but only the last one applies. No big deal. wink

Ha, only one can be used there. Docker might allow multiple names on their side, but I've never seen that used.

>     * Perhaps the `--help` docs might need to mention the default behaviour if you don't specify `--name`?

Good call out. I'll be sure to clarify it.

> One minor gripe _unrelated_ to `regctl` is that even when using `docker buildx build --dest type=oci,dest=my.tar --tag hello/world:v1.2.0` for a single-platform image, the tag isn't included in the `manifest.json`'s `RepoTags` that is generated either. Sigh. Will try my luck on that one with the buildx folks. sweat_smile

That's probably because of the new provenance that ships as a second manifest. You can disable that with `docker buildx build --provenance=false ...`.
