### ISSUE TITLE
[Question] How are we supposed to known the version since 0.4.7?

### ISSUE THREAD

**Issue by rgl** [regclient/regclient#383]
### Question

Since [v0.4.7](https://github.com/regclient/regclient/releases/tag/v0.4.7)/#304/#305 the tag/version was removed from the `regctl version` output and replaced with the git revision, e.g.:

```
VCSRef:     f43ada160d953317c51e7d9170afa2a316f4b9be
VCSCommit:  f43ada160d953317c51e7d9170afa2a316f4b9be
```

But, how, as a user, am I supposed to quickly known the version?

### Version

```text
VCSRef:     f43ada160d953317c51e7d9170afa2a316f4b9be
VCSCommit:  f43ada160d953317c51e7d9170afa2a316f4b9be
VCSState:   clean
VCSDate:    2023-02-26T02:43:41Z
Platform:   linux/amd64
GoVer:      go1.20.1
GoCompiler: gc
```

**Comment by sudo-bmitch** [comment]
Right now I don't have a good solution for this without comparing the commit hash to the tags in the git repo:

```
$ git show f43ada160d953317c51e7d9170afa2a316f4b9be
commit f43ada160d953317c51e7d9170afa2a316f4b9be (tag: v0.4.7, upstream/releases/0.4, releases/0.4)
Author: Brandon Mitchell <git@bmitch.net>
Date:   Sat Feb 25 21:37:17 2023 -0500

    Release v0.4.7
    
    Signed-off-by: Brandon Mitchell <git@bmitch.net>

...
```

We're currently waiting on a solution from https://github.com/golang/go/issues/50603. If it looks like this won't ever be fixed upstream, then it's possible to go back to injecting tag details with compiler flags.

**Comment by mwgamble** [comment]
I agree with @rgl, I don't think it's a good idea to wait on something that may never come. It's a perfectly reasonable expectation to be able to run `the-program --version` and get the actual version number of the software.
