### ISSUE TITLE
[Issue] Version subcommand does not print version since v0.4.7

### ISSUE THREAD

**Issue by nicholasdille** [regclient/regclient#386]
### Current Behavior

The output does not contain the version number:

```bash
$ ./regctl-linux-amd64 version
VCSRef:     f43ada160d953317c51e7d9170afa2a316f4b9be
VCSCommit:  f43ada160d953317c51e7d9170afa2a316f4b9be
VCSState:   clean
VCSDate:    2023-02-26T02:43:41Z
Platform:   linux/amd64
GoVer:      go1.20.1
GoCompiler: gc
```

### Expected Behavior

The output should contain the version number like v0.4.5 did:

```bash
$ ./regctl-linux-amd64 version
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```

### Steps To Reproduce

1. `curl -sLO https://github.com/regclient/regclient/releases/download/v0.4.7/regctl-linux-amd64`
2. `chmod +x regctl-linux-amd64`
3. `regctl-linux-amd64 version`

### Version

Happens since v0.4.7

```bash
$ ./regctl-linux-amd64 version
VCSRef:     f43ada160d953317c51e7d9170afa2a316f4b9be
VCSCommit:  f43ada160d953317c51e7d9170afa2a316f4b9be
VCSState:   clean
VCSDate:    2023-02-26T02:43:41Z
Platform:   linux/amd64
GoVer:      go1.20.1
GoCompiler: gc
```

### Environment

Only checked `amd64`

**Comment by sudo-bmitch** [comment]
This will be fixed with the next release.
