### ISSUE TITLE
Error: Digest missing from image reference

### ISSUE THREAD

**Issue by dmarteau** [regclient/regclient#39]
As described , the `image delete command <host>/<repo>:<tag>` is expected to remove a given tag from the registry but the only result I have (on private registry) is:
```
docker-regctl -v debug image delete <host>/<repo>:<tag>
DEBU[0000] Loaded default config                         config="&{/root/.regctl/config.json 0 map[] <nil> <nil>}"
DEBU[0000] Docker creds loaded                          
DEBU[0000] regclient initialized                        
DEBU[0000] Image digest                                  host="<host>" repo=<repo> tag=<tag>
Error: Digest missing from image reference
```
However when asking for digest for the same tag I get a result:
```
docker-regctl -v debug image digest <host>/<repo>:<tag>
DEBU[0000] Loaded default config                         config="&{/root/.regctl/config.json 0 map[] <nil> <nil>}"
DEBU[0000] Docker creds loaded                          
DEBU[0000] regclient initialized                        
DEBU[0000] Image digest                                  host=<host>" repo=<repo> tag=<tag>
DEBU[0000] Sending request                               method=HEAD url="https://<host>/v2/<repo>/manifests/<tag>" withAuth=false
sha256:8d81defd4a3609b44646c0b61c4cdb3c5e062ae1d432a59bb34a80d983f2742d
```

What I'm missing here ?

**Comment by sudo-bmitch** [comment]
The `regctl image delete` command will delete the entire image, or manifest, not just a tag (you can have multiple tags pointing to the same manifest). To specify the image to delete, you include the digest rather than just the mutable tag. This is an extra step, but it allows you to verify you are deleting the correct image and that a race condition doesn't change the tag point to an image you wanted to preserve. The resulting syntax looks like:

```
docker-regctl -v debug image delete <host>/<repo>@sha256:8d81defd4a3609b44646c0b61c4cdb3c5e062ae1d432a59bb34a80d983f2742d
```

**Comment by sudo-bmitch** [comment]
Also be careful when deleting multi-platform images, you want to delete the manifest list digest, and not the platform specific digest within a manifest:

```
digest=$(regctl image digest --list ${image_tag} | tr -d '\r')
regctl image delete ${image_tag}@${digest}
```

(The `tr -d '\r'` handles the cases where `regctl` is run as a docker container with the `-it` option.)

**Comment by sudo-bmitch** [comment]
For deleting a single tag, you can use `regctl tag delete ${image_tag}`.

**Comment by dmarteau** [comment]
Thank you very much for your explanation !

I was confused because of the docker cli syntax `docker image rm <tag>` which is quite similar.
