### ISSUE TITLE
[Feature] Interactive progress display for image copy

### ISSUE THREAD

**Issue by electrum** [regclient/regclient#390]
It would be nice if `regctl image copy` (and possibly other commands) could show progress, similar to how `docker pull` shows progress when downloading images. I can use the Network tab of Activity Monitor on macOS to see that the process is doing something, but more direct progress reporting would be nice.

**Comment by sudo-bmitch** [comment]
Thanks for the suggestion @electrum. I've added a progress display on the image copy in the latest commits. This does require a tty. This did require reordering some steps for a more accurate display of outstanding blobs to copy, and I'm working through the edge cases that resulted with at least one registry operator now. If you encounter any issues of your own, let me know.
