### ISSUE TITLE
WithRegOpts current not effect

### ISSUE THREAD

**Issue by lengrongfu** [regclient/regclient#410]
In this pr https://github.com/regclient/regclient/pull/408 `WithRegOpts` logic is:
```go
// WithRegOpts passes through reg.Opts to the reg client
func WithRegOpts(opts ...reg.Opts) Opt {
	return func(rc *RegClient) {
		if rc.regOpts == nil {
			rc.regOpts = []reg.Opts{}
		}
		rc.regOpts = append(rc.regOpts, opts...)
	}
}
```

In this pr https://github.com/regclient/regclient/pull/409 `WithRegOpts` logic is:
```go
// WithRegOpts passes through opts to the reg scheme
func WithRegOpts(opts ...reg.Opts) Opt {
	return func(rc *RegClient) {
                // when regOpts not element, will never execute the following line :rc.regOpts = append(rc.regOpts, opts...)
		if len(rc.regOpts) == 0 {
			return
		}
		rc.regOpts = append(rc.regOpts, opts...)
	}
}
```

@sudo-bmitch Can you tell me what the reason for the modification is?

**Comment by sudo-bmitch** [comment]
Mea culpa! I misread the first as validating the input `opts` and cleaned it up to just return if it's nil or empty. `rc.regOpts` should never be `nil` since `New` defines it here: https://github.com/regclient/regclient/blob/e7fedc5318444933799ef710722f2a89eda64dd4/regclient.go#L53

**Comment by sudo-bmitch** [comment]
Sorry for the mixup on that one and thanks for letting me know about it so quickly. If I missed anything else, don't hesitate to let me know, and thanks again for the original PR!
