### ISSUE TITLE
[Feature] Support authenticating to registries with client certificates

### ISSUE THREAD

**Issue by bpfoster** [regclient/regclient#450]
### Current Behavior
Only username/password-based authentication is supported.

### Expected Behavior

Some registries may be configured to require mTLS client certificates to authenticate instead.  It would be nice to have this support.

### Version

```text
VCSTag:     v0.4.8
VCSRef:     847254c7ac7d6f027dcdfb196a9aa4c11eb61ed9
VCSCommit:  847254c7ac7d6f027dcdfb196a9aa4c11eb61ed9
VCSState:   clean
VCSDate:    2023-04-14T23:41:20Z
Platform:   linux/amd64
GoVer:      go1.20.3
GoCompiler: gc
```

### Environment

- Running as binary or container: binary
- Host platform: Linux x86
- Registry description: private

**Comment by sudo-bmitch** [comment]
This is straight-forward to add. If this is for regctl, does a flag similar to `regctl registry set --cacert` (but for client cert/keys) work?

**Comment by bpfoster** [comment]
Great!  Yep for regctl, and I think flags like that would work fine.

**Comment by sudo-bmitch** [comment]
This should now be supported in the main branch. Let me know if you encounter any issues. Thanks for the suggestion!

**Comment by bpfoster** [comment]
Looks like it's working perfectly.  Thanks for the quick fix!
