### ISSUE TITLE
Registry login failure on Windows...

### ISSUE THREAD

**Issue by mestebangutierrez** [regclient/regclient#46]
Whenever I try to login to a registry, after passing the username I get the following failure:

```
$ regctl registry login [REDACTED]
Enter Username: [REDACTED]
Enter Password: The handle is invalid.
```

Issue seems similar to https://github.com/lightningnetwork/lnd/issues/498. When reading the password the client assumes `stdin` is FD `0` instead of resolving it via `syscall`:
https://github.com/regclient/regclient/blob/3051bd6c43207d2b6829f70a41ff8bc92e75f79b/cmd/regctl/registry.go#L156 

Version:

```
$ regctl version
{
  "VCSRef": "5a6a1d95524b9c1c2d38a5af7ab744742f8d55e9",
  "VCSTag": "v0.3.0"
}
```

**Comment by sudo-bmitch** [comment]
Thanks for the report! Looks like I copy and pasted from the wrong place.

**Comment by mestebangutierrez** [comment]
Is there any ETA for a release with the fix?

**Comment by sudo-bmitch** [comment]
Just pushed: https://github.com/regclient/regclient/releases/tag/v0.3.1

Let me know if it gives you any trouble. Also as a workaround, you can pass the `-p` flag to `regctl registry login` or manually edit the `~/.regctl/config.json`.

**Comment by sudo-bmitch** [comment]
Well shucks, the windows build failed. Looks like I need a type cast. I'll do some more testing on this tomorrow and push another update.

**Comment by sudo-bmitch** [comment]
Attempt 2 went better. If it gives you any trouble, let me know. Thanks again for the report!
https://github.com/regclient/regclient/releases/tag/v0.3.2

**Comment by mestebangutierrez** [comment]
Sorry for replying so late, but I didn't see the status update.

It now works on Windows terminal, but it still seems to fail within the **[mintty terminal emulator](https://mintty.github.io/)** included in my [Git for Windows](https://gitforwindows.org/) installation (which includes [MSYS2](https://www.msys2.org/)). I've also tried within a _Visual Studio Code_ terminal with the same Bash powered by my Git for Windows installation, and it works as well. 

The **mintty** terminal announces itself through the `TERM_PROGRAM` environment variable as `mintty`, and the particular version via the `TERM_PROGRAM_VERSION`, being in my current setup `3.4.0`.

Similarly, the Visual Studio Code terminal announces as `vscode` and in my current setup is `1.55.2`.

Thus, I think there is still a corner case yet to be addressed in Windows: supporting "[pseudo-terminals](https://en.wikipedia.org/wiki/Pseudoterminal)" (`pty`) like the one provided by **mintty** (MSYS2), which is extensively used, and others like that of **[Cygwin](https://cygwin.com/)**.

Some stuff, that may help:
* **Linux terminals, tty, pty and shell** blog posts ([part 1](https://dev.to/napicella/linux-terminals-tty-pty-and-shell-192e) and [part 2](https://dev.to/napicella/linux-terminals-tty-pty-and-shell-part-2-2cb2)), which provide interesting background on the topic.
* **[go-isatty](https://github.com/mattn/go-isatty)** a library that seems to identify Cygwin/MSYS2 pseudo-terminals.

**Comment by sudo-bmitch** [comment]
It sounds like this might be a working as designed issue with mintty. Docker seems to have faced the same issue with their registry login command: https://github.com/moby/moby/issues/15272#issuecomment-221431703

I came across that from a comment when looking at the similar code they use for handling password prompts: https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/registry.go#L120-L126

The code that I'm using for this is pretty straight forward: https://github.com/regclient/regclient/blob/32c91f4c1ce1024279e5269abc491bb8bf71d62f/cmd/regctl/registry.go#L155-L167

Unfortunately, the tty integration is all using the upstream Go libraries where everyone says wintty just doesn't work: https://github.com/golang/go/issues?q=is%3Aissue+mintty+

It's looking like the best I can do is improve that error message with something more user friendly and direct users to try something other than mintty. If there are better options, I'm happy to consider PRs.

**Comment by sudo-bmitch** [comment]
To try to updated binaries, you can download them directly from the CI on main. Here's today's run (note, these get automatically pruned after 7 days): https://github.com/regclient/regclient/actions/runs/803337315
