### ISSUE TITLE
[Issue] Error syncing images with annotations from Docker Hub to GCR

### ISSUE THREAD

**Issue by jeromefroe** [regclient/regclient#466]
### Current Behavior

When `regsync` is used to sync an image whose manifest contains an `annotations` field to GCR it fails with the following error:

```text
Failed to deserialize application/vnd.docker.distribution.manifest.list.v2+json
```

From what I can tell this is because [the `annotations` field isn't part of the official spec for a manifests list](https://github.com/moby/buildkit/issues/1143#issuecomment-522776087) and GCR is rejecting the manifest when `regsync` tries to `PUT` it. The reason the field is set at all is because Docker Hub appears to allow it:

```console
$ curl -LH "Authorization: Bearer ${TOKEN}" \
  -H "Accept: application/vnd.docker.distribution.manifest.v1+json,application/vnd.oci.image.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json" \
  "https://index.docker.io/v2/clickhouse/clickhouse-keeper/manifests/23.5.2.7"
{
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:f88b665f6009f7b2c3ece224159cdbdb631019b1abcd579a39ddb041c0aadb1b",
      "size": 1431,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:921ff55bb567b75e5b35d614f0a32b1a56fea821fb7df9068c88917d7bb96e19",
      "size": 566,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:f88b665f6009f7b2c3ece224159cdbdb631019b1abcd579a39ddb041c0aadb1b",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    },
    ...
```

### Expected Behavior

This isn't a problem with `regsync`, but it would be nice to have a way to work around it so that the sync could ignore the unsupported fields. Alternatively, instead of ignoring the unsupported fields, I also noticed during testing that if I removed the `application/vnd.docker.distribution.manifest.list.v2+json` media type from the `Accept` header that is sent in the initial `GET` request for the manifest, Docker Hub would respond with a manifest in the `application/vnd.oci.image.index.v1+json` media type and that manifest could be successfully sync'ed to GCR.

### Steps To Reproduce

I've observed this issue with the `clickhouse/clickhouse-server:23.5.2.7` image and can reliably reproduce by running `regsync once -c config.yml` where the contents of the config file are:

```yaml
creds:
  - registry: gcr.io
    repoAuth: true
sync:
  - source: clickhouse/clickhouse-server
    target: gcr.io/<some-registry>/clickhouse-server
    type: repository
    tags:
      allow:
        - "23.5.2.7"
```

### Version

I confirmed this is an issue on HEAD:

```text
$ ./bin/regsync version
VCSTag:     (devel)
VCSRef:     25b923cdbf4aedf64aad9a4d2b1a17b52146124b-dirty
VCSCommit:  25b923cdbf4aedf64aad9a4d2b1a17b52146124b
VCSState:   dirty
VCSDate:    2023-06-12T12:51:53Z
Platform:   darwin/arm64
GoVer:      go1.20.4
GoCompiler: gc
```

### Environment

- Running as binary or container: Binary
- Host platform: Mac
- Registry description: Syncing images from Docker Hub to GCR

**Comment by sudo-bmitch** [comment]
Anything that mutates the image risks dramatically slowing down regsync since it would have to mutate the image every time to see if it's changed from the previous time. So while I'm considering it, I'm also very hesitant.

For this specific issue, I'd look at how the image was built. If buildkit is generating images with `application/vnd.docker.distribution.manifest.list.v2+json` that contain `application/vnd.oci.image.manifest.v1+json`, that should probably be fixed. The manifest list would preferably have `application/vnd.oci.image.index.v1+json` as the mediaType to match the manifests in the list.

You can convert the image mediaTypes to their OCI verseions with:

```
regctl image mod --to-oci clickhouse/clickhouse-server:23.5.2.7 --replace
```

Or with the current main branch / edge images, the following can be used to modify the image while copying it:

```
regctl image mod --to-oci clickhouse/clickhouse-server:23.5.2.7 --create gcr.io/<some-registry>/clickhouse-server:23.5.2.7
```

**Comment by jeromefroe** [comment]
> Anything that mutates the image risks dramatically slowing down regsync since it would have to mutate the image every time to see if it's changed from the previous time. So while I'm considering it, I'm also very hesitant.

Totally understandable! Perhaps it wouldn't be as worrisome if we made the behavior opt-in? Though just to be clear too I'm not saying this approach is the right one, just that it might be worth making the behavior configurable if you do think it's best.

> For this specific issue, I'd look at how the image was built.

Unfortunately I don't have control over the build process for the original image, it's a third-party image that I'm just copying into an internal registry. With that being said though, I can take a look into their repo to try and get a better idea of how they're building the images.

> If buildkit is generating images with application/vnd.docker.distribution.manifest.list.v2+json that contain application/vnd.oci.image.manifest.v1+json, that should probably be fixed.

Yea, that's the case here 😢 

> The manifest list would preferably have application/vnd.oci.image.index.v1+json as the mediaType to match the manifests in the list.

The behavior of Docker Hub is pretty odd here (this may very well be just a reflection of my own ignorance of the Docker registry API's 😅) . During testing I noticed that if I removed `application/vnd.docker.distribution.manifest.list.v2+json` from the list of accepted media types it returned a `application/vnd.oci.image.manifest.v1+json` object instead (though not a `application/vnd.oci.image.index.v1+json` object):

```console
$ curl -LH "Authorization: Bearer ${TOKEN}" \
  -H "Accept: application/vnd.docker.distribution.manifest.v1+json,application/vnd.oci.image.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.oci.image.index.v1+json" \
  "https://index.docker.io/v2/clickhouse/clickhouse-keeper/manifests/23.5.2.7"
{
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:e853f03862c7c1b5f3257ef3372340bad698e5bab7615644217741af3e3e5fc0",
    "size": 9296
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
```

**Comment by sudo-bmitch** [comment]
Here's the bug: https://github.com/ClickHouse/ClickHouse/blob/607f337d67c5353a7caca93c6c1d5a03da684c48/tests/ci/docker_server.py#L296-L299

Which was just fixed in the latest buildx 0.11.0 release: https://github.com/docker/buildx/pull/1797

**Comment by jeromefroe** [comment]
> Here's the bug: https://github.com/ClickHouse/ClickHouse/blob/607f337d67c5353a7caca93c6c1d5a03da684c48/tests/ci/docker_server.py#L296-L299
> 
> Which was just fixed in the latest buildx 0.11.0 release: [docker/buildx#1797](https://github.com/docker/buildx/pull/1797)

Oh, that's great! Thanks for the pointer 🙏 I can follow up with the upstream about upgrading to buildx 0.11.0.

**Comment by sudo-bmitch** [comment]
I'm closing this out since it needs to be resolved either on the CLickHouse or (less likely) GCR side. For a one-off copy:

```
regctl image mod --to-oci clickhouse/clickhouse-server:23.5.2.7 --create gcr.io/<some-registry>/clickhouse-server:23.5.2.7
```

should help, using the latest regctl release.

The ability to mutate images with regsync is still on my list of things I'm considering, but I'd want to find a way to do that which doesn't require pulling/pushing every image on every sync.

**Comment by jeromefroe** [comment]
Sounds good to me, thank you for the help @sudo-bmitch!
