### ISSUE TITLE
[Feature] Add ability to test tag `allow` statements (mainly for regexes)

### ISSUE THREAD

**Issue by komapa** [regclient/regclient#469]
We are using the regsync utility with great success but we run into the problem where people are adding `allow` for what to sync but they end up syncing a lot more than they wanted. Example will be where you want to sync version `1.9.0` but then you do not realize there is also many different suffixes to that tag that you did not want.

### Expected Behavior

If we can have something native to `regctl tag ls` that does either `--regex` or `--filter` that runs the tags through the exact same logic as the regsync config file, that would be amazing improvement.

```
❯ ./bin/regctl tag ls hashicorp/vault-secrets-operator | grep -E "0.\\d+.\\d+-*"
0.1.0
0.1.0-beta
0.1.0-beta.1
0.1.0-rc.1
❯ ./bin/regctl tag ls hashicorp/vault-secrets-operator | grep -E "0.\\d+.\\d+-.*"
0.1.0-beta
0.1.0-beta.1
0.1.0-rc.1
```

### Example Solution

```
./bin/regctl tag ls hashicorp/vault-secrets-operator --regex "0.\\d+.\\d+-.*"
./bin/regctl tag ls hashicorp/vault-secrets-operator --filter "0.\\d+.\\d+-.*"
```

**Comment by sudo-bmitch** [comment]
Thanks for the suggestion! I've added this in #477. To match regsync, multiple include and exclude options are allowed. If you encounter any issues with it, let me know.
