### ISSUE TITLE
[Issue] Import all containers in export tar

### ISSUE THREAD

**Issue by zlmitchell** [regclient/regclient#480]
### Current Behavior
At some point in the past I was able to get the manifest.json from a combined export tar image of multiple images. Loop over the images and target the tar, which then would push each image in turn to a target remote registry.

Currently right now this behavior only grabs the first image in the combined manifest.

### Expected Behavior

If you have a list of images in a combined image export (from docker or podman). `regctl` should be able to import said list of images one by one into a target registry using the combined tar.

### Steps To Reproduce

Create Combined Archive
```bash
podman save -m quay.io/metallb/controller:v0.13.9 quay.io/metallb/speaker:v0.13.9 docker.io/library/registry:2.8.2 -o combined.tar
```

look at manifest.json
```bash
tar xf combined.tar manifest.json
cat manifest.json | jq
```

```json
[
  {
    "Config": "26952499c3023d9c7520c0cff480b3be67567d0cd85453d5dc83f08587c43767.json",
    "RepoTags": [
      "quay.io/metallb/controller:v0.13.9"
    ],
    "Layers": [
      "7cd52847ad775a5ddc4b58326cf884beee34544296402c6292ed76474c686d39.tar",
      "eccf84470f96d7ffcc62a33c02a72e07da6a5800e672490675b46a93a2ee9473.tar",
      "6676f4c7582ddd3c245a546d87862217d1088ec901b57f61201d4e4aec412b0f.tar"
    ]
  },
  {
    "Config": "697605b359357289e5fc3737397f69b00dae7d23db5cc74ddf2f5702acf7ad63.json",
    "RepoTags": [
      "quay.io/metallb/speaker:v0.13.9"
    ],
    "Layers": [
      "7cd52847ad775a5ddc4b58326cf884beee34544296402c6292ed76474c686d39.tar",
      "8c4a4529824aa4f49754f0e61e8d79d5ad94785fab1664aa4c52a83b4c87d287.tar",
      "91e1f0ad9fafc898a5d6339e448d15bc0a646370a4c16019021e298150fca228.tar",
      "95ae25ab39424d11b79b74d5a22259b2da25d1a75a7203d153a92bef4fe147cc.tar",
      "1fd46815b46fd90b561ef268d2668ddf9565b38d1d48d5421f460be24a1cc9be.tar"
    ]
  },
  {
    "Config": "65f3b3441f044d142ca365389fe0532900b4f4c7ffc47cb65f7bc7bd45857f06.json",
    "RepoTags": [
      "docker.io/library/registry:2.8.2"
    ],
    "Layers": [
      "bb01bd7e32b58b6694c8c3622c230171f1cec24001a82068a8d30d338f420d6c.tar",
      "4984fbd72df141afc1ae10f6c542b08aa55affab51807799c0395f99917d62b8.tar",
      "f8dc4f9c98a6b5688fe17f71745c132282282607edbe40e1e4939d9eedef3a0d.tar",
      "744dbed40ffa1dfe854eac1de2fbb29e72afd71066f3a55e5aac3033f09c39bf.tar",
      "6e5160500bc7355642c29d51ce547e9ff3123d1b480505aebaa32f747529e937.tar"
    ]
  }
]
```

Loop over manifest.json and import the images into a target registry, example we will try the 2nd image in the list

```bash
regctl image import <TARGETREGISTRY>/metallb/speaker:v0.13.9 combined.tar
```

check the target registries manifest for layers.

```bash
podman manifest inspect <TARGETREGISTRY>/metallb/speaker:v0.13.9
```

Layers are the same as first image in archive

### Version

```text
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```

### Environment

Platform: linux
Registry: registry:2 container in kubernetes

### Anything else

Sorry if i have a command messed up somewhere, we were using the golang libraries to do this, and it seems to not be working anymore :( Let me know if i've missed something

**Comment by sudo-bmitch** [comment]
If this used to be supported by regctl, I'd be curious what version that was in. Outputting to an OCI directory and labeling each manifest with a different tag would be the easiest, because then it could be copied with:

```
regctl image copy ocidir://${dir}:${tag} ${dest}:${tag}
```

But looking at the podman documentation, I don't believe that's an option.

Adding the ability to select one image from a list should be fairly straight forward to add.

**Comment by zlmitchell** [comment]
Podman or docker export from tar to import into a target registry is what we thought we had built about 8 months ago. Whether it be a full copy of all images in the tarball or the ability to select a specific image from the tarball would be out use case.

One of our developers thinks it may be in the images.go when things are referencing `trd.doxkerManifestList[0]` that this may be our issue...

**Comment by sudo-bmitch** [comment]
Yes, the image.go does the import and always picks the first image today. Changing that to support importing an arbitrary image from the tar can be added and I've got that on my list.
