### ISSUE TITLE
image get-file does not return all the file or from wrong layer

### ISSUE THREAD

**Issue by dick-twocows** [regclient/regclient#502]
### Current Behavior

regctl image get-file returns the following message and the file returned doe snot match the actual file contents.

digest mismatch, expected sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3, received sha256:773ea7c73be93df8e255e646414e34ab72e8fd72c1e3cfdeb8c3f1a96187a645 error returned when attempting to get a file from image.

A file is returned but it is not the file returned by running cat /etc/hosts on the running container.

### Expected Behavior

No digest mismatch and the file returned has the correct contents.

### Steps To Reproduce

<hello-world-go/xgo_build on  COMUK-1000 [$✘!?] 
❯ cat /tmp/foo
cat: /tmp/foo: No such file or directory

hello-world-go/xgo_build on  COMUK-1000 [$✘!?] 
❯ ./regctl version
VCSTag:     v0.5.0
VCSRef:     c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb
VCSCommit:  c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb
VCSState:   clean
VCSDate:    2023-06-28T17:37:27Z
Platform:   darwin/amd64
GoVer:      go1.20.5
GoCompiler: gc

hello-world-go/xgo_build on  COMUK-1000 [$✘!?] 
❯ docker run alpine:latest cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	6df3b6218f51

hello-world-go/xgo_build on  COMUK-1000 [$✘!?] 
❯ ./regctl image get-file alpine:latest /etc/hosts -v debug >/tmp/foo
DEBU[0000] Loading docker config                         api= blobChunk=0 blobMax=0 helper=docker-credential-osxkeychain hostname=sretooling-imaging-release-docker-local.artifactory-builds.oci.oraclecorp.com mirrors="[]" name=sretooling-imaging-release-docker-local.artifactory-builds.oci.oraclecorp.com pathPrefix= repoAuth=false tls=enabled user=rimurray
DEBU[0000] regclient initialized                         VCSRef=c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb VCSTag=v0.5.0
DEBU[0000] Get file                                      filename=etc/hosts ref="docker.io/library/alpine:latest"
DEBU[0000] http req                                      method=GET url="https://registry-1.docker.io/v2/library/alpine/manifests/latest" withAuth=false
DEBU[0001] Auth request parsed                           challenge="[{bearer map[realm:https://auth.docker.io/token scope:repository:library/alpine:pull service:registry.docker.io]}]"
DEBU[0002] http req                                      method=GET url="https://registry-1.docker.io/v2/library/alpine/manifests/latest" withAuth=true
DEBU[0002] http req                                      method=GET url="https://registry-1.docker.io/v2/library/alpine/manifests/sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70" withAuth=true
DEBU[0003] http req                                      method=GET url="https://registry-1.docker.io/v2/library/alpine/blobs/sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3" withAuth=true
digest mismatch, expected sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3, received sha256:773ea7c73be93df8e255e646414e34ab72e8fd72c1e3cfdeb8c3f1a96187a645

hello-world-go/xgo_build on  COMUK-1000 [$✘!?] took 3s 
❯ cat /tmp/foo
127.0.0.1	localhost localhost.localdomain
::1		localhost localhost.localdomain

hello-world-go/xgo_build on  COMUK-1000 [$✘!?] 
❯ 

### Version

hello-world-go/xgo_build on  COMUK-1000 [$✘!?] 
❯ ./regctl version
VCSTag:     v0.5.0
VCSRef:     c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb
VCSCommit:  c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb
VCSState:   clean
VCSDate:    2023-06-28T17:37:27Z
Platform:   darwin/amd64
GoVer:      go1.20.5
GoCompiler: gc

### Environment

❯ uname -a
Darwin rimurray-mac 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

**Comment by sudo-bmitch** [comment]
I'll look into the digest mismatch error. The content in the file is from the image, and in a container, /etc/hosts is mounted by docker since it manages that file for features like `--link`.

**Comment by sudo-bmitch** [comment]
Thanks for the report. I've fixed the digest error in #503. The error in the current versions can be ignored. It's comparing the digest of the full blob to a partially read blob, which will always fail unless fetching the file causes the full blob to be read.
