### ISSUE TITLE
[Feature] Support import and export compressed tar file

### ISSUE THREAD

**Issue by fanthos** [regclient/regclient#519]
I just found this project is very useful on air-gapped environment when docker not installed on my computer. Currently `regctl image` does not support compressed tar file. Usually compressed file is used when transfer large images between enviornments. Compressed file size is only 30% of original file size for many images.

### Current Behavior

I have to uncompress tar.gz file to tar file before upload the image to registry.

`regctl import` and `regctl export` supports only uncompressed tar file.

### Expected Behavior

`regctl import` and `regctl export` can use compressed tar file like `.tar.gz` or `.tar.xz`.

### Version
0.5.1 windows/amd64

**Comment by fanthos** [comment]
Docker does not support it by it self, so I load the compressed file by using something like `cat img.tar.gz | gzip -d | docker load `

**Comment by sudo-bmitch** [comment]
This should be done in the latest commit to main. If you have any issues with it, let me know.
