### ISSUE TITLE
can i override entrypoint without starting a container ?

### ISSUE THREAD

**Issue by teto** [regclient/regclient#532]
### Question

I've got an issue that is slowly driving me insane: I want to override the entrypoint of an IMAGE without having to start a container. The entrypoint is a property of the image so why would I need to start a container (https://github.com/opencontainers/image-spec/blob/main/config.md) ?! (alternative being to do a docker build on a file that imports the previous image)
I've looked at buildah/skopeo/crane to no avail . So my question is : can I do `regctl mod <MYIMAGE> entrypoint=/bin/sh` and get a new image with the new entrypoint ?

**Comment by sudo-bmitch** [comment]
The traditional solution would be to build a new image:

```Dockerfile
FROM some_image
ENTRYPOINT [ "/bin/sh" ]
```

I do see `crane mutate --entrypoint /bin/sh $some_image`.

Right now, I don't have a `regctl image mod` option for this yet, but it's easy enough to add.

**Comment by teto** [comment]
It looked to me that `crane mutate` also worked on container IDs rather than image ids. I actually gave up and used nix to rebuild the same image with a different entrypoint so I dont need it anymore (at least for now). 

```
FROM some_image
ENTRYPOINT [ "/bin/sh" ]
```
For some reason I dont like that, maybe because I am not sure how it works. I suppose it doesn't create any layer and just updates the config but I feel it should be easier / just a command line so if `regctl image mod` could do it, at least it would be the only tool capable of such a thing.

**Comment by teto** [comment]
(feel free to close depending on whether you wanna support that)

**Comment by sudo-bmitch** [comment]
I finally got around to implementing this one. Thanks for the suggestion!
