### ISSUE TITLE
[Question] regctl repo ls does not list docker.io repos

### ISSUE THREAD

**Issue by outsinre** [regclient/regclient#539]
### Question

I want to list repos on "docker.io" with command.

```bash
ubuntu:~$ regctl registry config
{
  "docker.io": {
    "tls": "enabled",
    "hostname": "registry-1.docker.io",
    "user": "foo",
    "credHost": "https://index.docker.io/v1/",
    "reqPerSec": 10,
    "reqConcurrent": 3
  }
}
ubuntu:~$ regctl repo ls docker.io
WARN[0001] Sleeping for backoff                          Host=docker.io Seconds=1.999988708
WARN[0004] Sleeping for backoff                          Host=docker.io Seconds=3.999995195
failed to list repositories for docker.io: unauthorized
```

I am sure I have ran `regctl registry login`.

### Version

```text
VCSTag:     v0.5.1
VCSRef:     3aa6a4c4486eed78dd00f13e953ffad37cb4677e
VCSCommit:  3aa6a4c4486eed78dd00f13e953ffad37cb4677e
VCSState:   clean
VCSDate:    2023-08-06T14:47:14Z
Platform:   linux/amd64
GoVer:      go1.20.7
GoCompiler: gc
```

### Environment

- Running as binary or container: binary
- Host platform: macOS or AWS Ubuntu 22.04
- Registry description: docker.io

**Comment by sudo-bmitch** [comment]
Docker Hub, and many other cloud registries, does not support the `_catalog` API. And regclient doesn't use registry specific APIs that would only work on Hub and not other OCI registries. Eventually OCI may define APIs that cloud vendors will support, likely scoped to a user account. But until then, this is not expected to work on Hub.

**Comment by outsinre** [comment]
@sudo-bmitch thanks for the instant response. So, this is expected and not supported so far.

I will close this issue.
