### ISSUE TITLE
[Feature Request] Support credHelpers

### ISSUE THREAD

**Issue by eriksw** [regclient/regclient#54]
It'd be really nice if regctl supported Docker credential helpers.

Specifically, if I've already set up my `~/.docker/config.json` with something like this:

```
{
  "credHelpers" : {
    "us-docker.pkg.dev" : "gcloud",
    "xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com" : "ecr-login"
  },
  ...
}
```

It'd be great if regclient would default to using those credential helpers so that it "just works" out of the box in situations where the following would work due to docker using the configured helpers:
```
docker pull xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/foo \
&& docker tag docker.pkg.dev/foo xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/foo \
&& docker push docker.pkg.dev/foo
```

**Comment by sudo-bmitch** [comment]
Thanks for the suggestion! This should be working from the latest build on main. You can pull the binaries directly from the build artifacts for the next few days to test. https://github.com/regclient/regclient/actions/runs/896068607
