### ISSUE TITLE
[Feature] Pass registry credentials to `regctl image inspect` through CLI flags

### ISSUE THREAD

**Issue by felipecrs** [regclient/regclient#552]
It's cool that `regctl` can read my credentials from the `~/.docker/config.json`, but for some of my automation scripts, I don't want to `docker login` in the machine just to retrieve some label from the remote image.

It would be awesome if we had some flags like `skopeo inspect` has `--username` and `--password`. Note that I would much like prefer to use regclient and it is so much smaller than skopeo itself:

```console
❯ docker images
REPOSITORY                 TAG            IMAGE ID       CREATED        SIZE
quay.io/skopeo/stable      latest         6fc85a8ac6da   7 hours ago    328MB
regclient/regctl           v0.5.2         ca8e22728946   2 days ago     9.65MB
```

**Comment by sudo-bmitch** [comment]
There is `regctl registry login` to store the credentials without docker. Since some commands like `regctl image copy` can work on multiple repositories, adding a flag for this may be complicated.

**Comment by felipecrs** [comment]
Maybe for now we add these flags only to `regctl image inspect` and the other commands that works with a single image ref.

For reference, `skopeo inspect` has `--username`, but `skopeo copy` has `--src-username` and `--dest-username`.

**Comment by sudo-bmitch** [comment]
Hopefully the `--host` flag resolves this for you. It can be passed multiple times for multiple registries to handle the challenge that some commands interact with multiple registries. This only supports user, pass, and tls for now, but other configuration settings could be added.

**Comment by felipecrs** [comment]
Oh, that's a very interesting and clever approach. It surely works for me. Thank you.
