### ISSUE TITLE
[Feature] `regctl image size`

### ISSUE THREAD

**Issue by felipecrs** [regclient/regclient#562]
This is a suggestion for a new command: `regctl image size`. Examples:

```console
# outputs uncompressed image size in bytes (like the one shown by 'docker images')
$ regctl image size alpine
7340000

# outputs compressed image size
$ regctl image size --compressed
3401967

# same but in human readable format
$ regctl image size --compressed -h
3.4MB
```

I don't know if such uncompressed size can actually be inferred without having to actually pull the image. If this is not possible, nevermind it. Consider the feature suggestion as only compressed size then.

I have some bash scripts that somewhat handles it with:

```console
docker manifest inspect --verbose docker.io/library/alpine:latest |
      jq -er 'if type == "array" then .[] else . end | select(.Descriptor.platform.architecture=="amd64") | .SchemaV2Manifest.layers[].size' |
      jq -s add
```

But it isn't very portable and actually does not work for all image manifests.

I think this would be a nice addition to regctl.

What do you think?

**Comment by felipecrs** [comment]
Here is another good reference: https://stackoverflow.com/a/73108928/12156188

**Comment by sudo-bmitch** [comment]
This is done in the formatted/pretty output of a manifest get for a specific platform:

```
$ regctl image manifest alpine --platform local
Name:        alpine
MediaType:   application/vnd.docker.distribution.manifest.v2+json
Digest:      sha256:48d9183eb12a05c99bcc0bf44a003607b8e941e1d4f41f9ad12bdcc4b5672f86
Total Size:  3.402MB
             
Config:      
  Digest:    sha256:8ca4688f4f356596b5ae539337c9941abc78eda10021d35cbc52659c74d9b443
  MediaType: application/vnd.docker.container.image.v1+json
  Size:      1472B
             
Layers:      
             
  Digest:    sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      3.402MB
```

The "total size" line is a sum of all of the layer sizes. Unfortunately there's no easy way to get the uncompressed size without putting the image. It's also not a good estimate of the download size when some layers may have already been pulled. It would be fairly straightforward to expose this size as either a separate command, or maybe a specific field in the formatted output that could be returned with a `--format ...` option. However it does require the platform to be specified for multi-platform images. Would that still be useful or do you need the uncompressed size too (i.e. to estimate a maximum disk usage)?

**Comment by felipecrs** [comment]
I have no use case for the uncompressed size. And if you wonder, my use for the compressed size is to predict how big would be to `regctl export` all the images from my project for sharing with customers using methods other than through a docker registry.

In this case, the reported compressed size is already good although not perfect:

```console
❯ regctl image export ghcr.io/felipecrs/jenkins-agent-dind:latest --platform local > jenkins-agent-dind.tar
❯ ls -lh jenkins-agent-dind.tar
-rw-r--r-- 1 felipecrs felipecrs 851M Oct  2 20:17 jenkins-agent-dind.tar
❯ regctl image manifest ghcr.io/felipecrs/jenkins-agent-dind:latest --platform local
Name:        ghcr.io/felipecrs/jenkins-agent-dind:latest
MediaType:   application/vnd.oci.image.manifest.v1+json
Digest:      sha256:669eee867e2f4b45c56e615b065f2b8432515606f9ff8b9e08c325416d566184
Total Size:  891.778MB
```

I am wondering if this difference could be an error during the calculation of the human readable size (maybe diving by 1000 instead of by 1024).

> maybe a specific field in the formatted output that could be returned with a --format ... option. 

Looks like the best thing to do, especially considering that this data is already part of the `regctl image manifest`, so it is expectable to be able to query it through `--format`.

The only problem however is that I would need the size in bytes to better script around it.

My suggestion is to keep the raw size to be queried with `--format` in bytes, but when not using `--format`, then you can pretty print it in a human readable format.

> However it does require the platform to be specified for multi-platform images.

Perfectly acceptable. In fact, this is even desired.

**Comment by felipecrs** [comment]
Ok, that seems to be exactly the case:

https://github.com/regclient/regclient/blob/b73766a737a0508aa6f6008cf2028b087ebca866/internal/units/size.go#L43

According to https://stackoverflow.com/a/73108928/12156188:

> sizes in manifests [are](https://docs.docker.com/registry/spec/manifest-v2-2/#image-manifest-field-descriptions) 1024-based

**Comment by sudo-bmitch** [comment]
Yes, the MB(1000) vs MiB(1024) vs M(????) challenge. A field exposed to `--format` would be in bytes, so that's easy enough to used any way need it.

**Comment by felipecrs** [comment]
Perhaps `--platform local --format {{ .TotalSize }}`

**Comment by sudo-bmitch** [comment]
> Amazing. Perhaps `--platform local --format {{ .TotalSize }}`?

I went with `.GetSize` to mirror the `.GetLayers` and `.GetConfig` methods. As long as it's an image, and not a manifest list / index, that should work (with the exclusion of the really old schema v1 docker images).

**Comment by felipecrs** [comment]
That's amazing, thanks a ton!

**Comment by felipecrs** [comment]
By the way, I would still recommend to change the default human-readable text to display MiB rather than MB. Or even drop the `iB` or `B` suffix.

That's to align with `ls -h`:

```
-h, --human-readable
         with -l and -s, print sizes like 1K 234M 2G etc.
--si   likewise, but use powers of 1000 not 1024
```

**Comment by felipecrs** [comment]
PS: it's just a suggestion. I will respect your preference. I just wanted to point the default for `ls`.
