### ISSUE TITLE
[Issue] regctl artifact get not working after put

### ISSUE THREAD

**Issue by KevinDMack** [regclient/regclient#563]
### Current Behavior

After putting an artifacting onto a registry using regctl artifact put, when I try to run a regctl artifact get, it returns that 
manifest does not support image methods.

### Expected Behavior

I would expect the regctl artifact get command would return the artifact.

### Steps To Reproduce

Current if  I run the following command:
```bash
regctl artifact put --artifact-type application/vnd.test.arm64.buildartifact -m application/vnd.test.arm64.buildartifact --annotation org.platform=arm64 --subject ghcr.io/test/nuget/test-package:0.1.0_arm64 --file ./test-package.nupkg
```
The command completes successfully, and I can see the digest of the image.  
regctl artifact get ghcr.io/test/test-package:0.1.0_arm64 --filter-artifact-type application/vnd.test.arm64.buildartifact 

And I get the following error back:
manifest does not support image methods

### Version

VCSTag:     v0.5.0
VCSRef:     c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb
VCSCommit:  c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb
VCSState:   clean
VCSDate:    2023-06-28T17:37:27Z
Platform:   linux/amd64
GoVer:      go1.20.5
GoCompiler: gc

### Environment

ubuntu linux
github packages registry

**Comment by sudo-bmitch** [comment]
Hi @KevinDMack. With the `--subject` on the put:

```shell
regctl artifact put --subject ghcr.io/test/nuget/test-package:0.1.0_arm64 ...
```

The `ghcr.io/test/nuget/test-package:0.1.0_arm64` image itself is not modified, but a manifest is pushed with the subject field set allowing it to be queried as a referrer to the image.

When pulling an artifact pushed like that, you need to also pass `--subject` to the `regctl artifact get`, e.g.:

```
regctl artifact get --subject ghcr.io/test/nuget/test-package:0.1.0_arm64 ...
```

Let me know if that solves your issue.

**Comment by KevinDMack** [comment]
Fantastic thanks, will run a test later tonight and respond back.  Appreciate the quick reply.
