### ISSUE TITLE
Don't swallow the error that resulted in BodyFunc re-initialization

### ISSUE THREAD

**Issue by edigaryev** [regclient/regclient#621]
Currently, when the `clientResp.Next()` encounters an error that might be re-tried, it re-initializes `BodyFunc`.

However, when the `rdr` is not seekable, the following code will return a pretty useless error to the `BlobPut()`s callee:

https://github.com/regclient/regclient/blob/f5f7e77201077f7a87bf28e3a15fb9cd1d375e6b/scheme/reg/blob.go#L393-L407

It seems that a more proper solution would be to define something like `ErrNotSeekable`, throw it in the snippet above, and handle it in `clientResp.Next()` by returning the last error that relates to the registry interaction (instead of the actual `ErrNotSeekable`).

**Comment by sudo-bmitch** [comment]
I've got something to try in #622. I'll revisit it over the next few days to see if I can add some tests to this before merging.

**Comment by sudo-bmitch** [comment]
Sorry for the delay, got distracted with some different test code, and if I realized how easy it was going to be to add the test I would have knocked it out immediately. This should now be fixed in main.
