### ISSUE TITLE
[Issue] unknown command "delete" for "regctl"

### ISSUE THREAD

**Issue by yanns** [regclient/regclient#626]
### Current Behavior

The help of `tag` indicates that the command `delete` exists:

```
$ ./regctl tag --help
manage tags

Usage:
  regctl tag [command]

Available Commands:
  delete      delete a tag in a repo
  ls          list tags in a repo
```

When trying to use the command `delete`, `regctl` outputs an error that this command is unknown:

```
./regctl -v tag delete <repo:tag>
unknown command "delete" for "regctl"
```

### Expected Behavior

If the command is documented, it should exist

### Steps To Reproduce

See above

### Version

```
regctl version
VCSTag:     v0.5.5
VCSRef:     278ecbfdfce3e8b89ac15348ffe750b823ee1ea9
VCSCommit:  278ecbfdfce3e8b89ac15348ffe750b823ee1ea9
VCSState:   clean
VCSDate:    2023-11-24T21:10:14Z
Platform:   linux/amd64
GoVer:      go1.21.4
GoCompiler: gc
```
### Environment

linux
Using GCR docker registry

**Comment by sudo-bmitch** [comment]
> ```
> ./regctl -v tag delete <repo:tag>
> unknown command "delete" for "regctl"
> ```

The `-v` flag for logging verbosity takes a parameter, like debug, info, warn, and error. Try passing a proper value to that, or remove the flag:

```
./regctl tag delete <repo:tag>
```

**Comment by yanns** [comment]
Something like that?
```
$ regctl -v info tag delete <repo:tag>
regctl: line 1: Not: command not found
```

**Comment by yanns** [comment]
Update: I guess it's another issue, as it's printing out "command not found" for all commands, including `version`.

**Comment by sudo-bmitch** [comment]
Make sure you have overwritten the regctl binary with something else.

**Comment by yanns** [comment]
Yes, sorry stupid mistake.
I can confirm that `-v debug` or `-v info` works:

```
regctl -v debug tag delete "<repo>tag>"
```
