### ISSUE TITLE
[Feature] Host level proxy support

### ISSUE THREAD

**Issue by cloorc** [regclient/regclient#628]
### Current Behavior

Some registry is on the internet and the connectivity could be not steady, so we need a `proxy` option for specific registry host in `.regctl/config.json` as following:

```
{
  "hosts": {
    "docker.io": {
      "tls": "enabled",
      "proxy": "socks5://127.0.0.1:1080"
    },
}
```

### Expected Behavior

As former description.

### Example Solution

1. Config as former description;
2. Using `regctl` as normal
3. Log proxy for host if a proxy is configured

### Version

```text
Next release would be appreciate.
```

### Environment

All platforms that `regctl` already supported are expected.

- Running as binary or container:
- Host platform: Linux/Windows

### Anything else

None

**Comment by cloorc** [comment]
> Hi @cloorc. Just to verify, on your network you have multiple proxy servers, each used for a different registry? The built-in Go capabilities would handle the scenario where you have one proxy for the external network, and various machines on the local network that aren't accessed with a proxy. And the mirroring configuration would handle the scenario where you have different mirrors for different hosts, rather than proxy servers.

Actually in my circumstance, there would be only one proxy server used for all external network and bypass all intranet servers. Sorry to declare that I'm not familiar with the built-in capability to proxy only for external networks. Could you please provide any related links? Thanks a lot!

**Comment by sudo-bmitch** [comment]
@cloorc 
> Actually in my circumstance, there would be only one proxy server used for all external network and bypass all intranet servers. Sorry to declare that I'm not familiar with the built-in capability to proxy only for external networks. Could you please provide any related links? Thanks a lot!

Go uses the `http_proxy`, `https_proxy`, and `no_proxy` environment variables, case insensitive, following the general conventions. I had broken that in v0.5.4, so make sure to test with the current version.

Here are some useful links on the topic:

- https://pkg.go.dev/golang.org/x/net/http/httpproxy
- https://superuser.com/questions/944958/are-http-proxy-https-proxy-and-no-proxy-environment-variables-standard
- https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

**Comment by cloorc** [comment]
> @cloorc
> 
> > Actually in my circumstance, there would be only one proxy server used for all external network and bypass all intranet servers. Sorry to declare that I'm not familiar with the built-in capability to proxy only for external networks. Could you please provide any related links? Thanks a lot!
> 
> Go uses the `http_proxy`, `https_proxy`, and `no_proxy` environment variables, case insensitive, following the general conventions. I had broken that in v0.5.4, so make sure to test with the current version.
> 
> Here are some useful links on the topic:
> 
> * https://pkg.go.dev/golang.org/x/net/http/httpproxy
> * https://superuser.com/questions/944958/are-http-proxy-https-proxy-and-no-proxy-environment-variables-standard
> * https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

OK，understood. Thanks a lot! But it seems more like a global setting rather than an application-specific setting and it will actually increse loading for user right? I still think this feature will be more flexible and explicit. Please have a look again. Thanks again!

**Comment by sudo-bmitch** [comment]
Based on the review of similar tools, I'm closing this as not planned. I think it makes more sense to use the built-in capabilities of Go rather than adding an alternate implementation.
