### ISSUE TITLE
[Question] Unable to set --tls=disabled on my private registry

### ISSUE THREAD

**Issue by SanadhyaLakshya** [regclient/regclient#631]
While running the command on my registry 

Command :  **regctl registry set --tls=disabled test.setup.svc:5000** 

i am getting : **mkdir /.regctl: permission denied**

Is there any way to give a specific path to regctl or how i can set the tls to disabled

**Comment by sudo-bmitch** [comment]
By default, regctl and the other commands use the user's home directory, specified by the `$HOME` environment variable. That location can be overridden by setting the `$REGCTL_CONFIG` variable to the path and filename you'd prefer. For one-off commands, there is an option to specify host parameters directly on the CLI with:

```shell
regctl --host reg=test.setup.svc:5000,tls=disabled tag ls test.setup.svc:5000/repo
```
