### ISSUE TITLE
Feature Request: Support for synchronizing docker registries

### ISSUE THREAD

**Issue by frakman1** [regclient/regclient#64]
I have a private docker registry using the docker contrainer `registry registry:2`. Let's call it `myregistry1`
I want to create a second identical registry, `myregistry2` but without disturbing the original running one. So no shutting down, cloning drive etc.

I can create a new, empty `myregistry2` on a second machine using the same docker container method `registry registry:2`

Can your tool be used (or upgraded and used) to copy all the docker images and associated metadata from `myregistry1` to `myregistry2` over the network, then keep it in sync going forward?

I was thinking of using this library or something similar to loop over all the images of `myregistry1` and push them to `myregistry2` but not sure how to do it.

**Comment by sudo-bmitch** [comment]
Thanks for the suggestion! `regsync` will get you part way there today, but you would need to list every repository to mirror, not just the registry. This could be scripted up with `regctl` or `regbot` with some work. The risk right now is the source registry needs to support the `_catalog` API request, which many cloud vendors don't, and didn't make it into the OCI distribution-spec. Fortunately the `registry:2` image does support that API so I think your use case is possible. I'll try adding this to `regsync` and follow up here when there's something to test.

**Comment by frakman1** [comment]
I'd love the chance to test this feature. I think it would be very welcome and useful in the broader community too. Thank you!

**Comment by sudo-bmitch** [comment]
This was easier than I thought it would be, at least for the regsync version. If you also want to delete old tags, that gets into regbot and a script to do that could be put together (I've been working on making some reusable Lua modules to make that easier, but I don't have those to a state that I'm ready to support just yet).

For testing this with regsync, the yaml syntax looks like:

```yaml
creds:
  # add other credentials and TLS settings here
  - registry: "registry-source:5000"
  - registry: "registry-target:5000"
sync:
  - source: "registry-source:5000"
    target: "registry-target:5000"
    type: registry
```

Then to test:

```shell
docker run --rm -v "$(pwd)/regsync.yml:/home/appuser/regsync.yml:ro" \
  regclient/regsync:edge -c /home/appuser/regsync.yml once
```

**Comment by frakman1** [comment]
It appears to work!

I created a source registry on a Pi (192.168.86.78:5001)
I then created a target registry on my Mac (192.168.86.31:5001)
I created them using the command: `$docker run -d -p 5001:5000 --restart=always --name registry registry:2`
I then pushed two test images to the source, `my-hello-world` and `my-nginx`

On the target. I first confirmed that it's empty
```
$curl -s localhost:5001/v2/_catalog | jq .
{
  "repositories": []
}
```

I used this configuration file:
```
$cat regsync.yml
creds:
  # add other credentials and TLS settings here
  - registry: "192.168.86.78:5001"
    tls: disabled
  - registry: "192.168.86.31:5001"
    tls: disabled
sync:
  - source: "192.168.86.78:5001"
    target: "192.168.86.31:5001"
    type: registry
```

Then I ran the command via docker:
```
$docker run --rm -v "$(pwd)/regsync.yml:/home/appuser/regsync.yml:ro" regclient/regsync:edge -c /home/appuser/regsync.yml once
Unable to find image 'regclient/regsync:edge' locally
edge: Pulling from regclient/regsync
e1b8a0972103: Pull complete
1ce12b0270e4: Pull complete
4d78fe50e885: Pull complete
0d87b2be25bb: Pull complete
Digest: sha256:77689973f60d8f8dcc91f1da58d39f891134f079c440d64deb3bd6117336bfcd
Status: Downloaded newer image for regclient/regsync:edge
time="2021-06-25T04:31:22Z" level=info msg="Image sync needed" source="192.168.86.78:5001/my-hello-world:latest" target="192.168.86.31:5001/my-hello-world:latest"
time="2021-06-25T04:31:22Z" level=info msg="Copy config" digest="sha256:851163c78e4ad68e6fe5391f0894aafd164d40c4d4d0a56b4291f0dc2c75cc2c" source="192.168.86.78:5001/my-hello-world" target="192.168.86.31:5001/my-hello-world"
time="2021-06-25T04:31:22Z" level=info msg="Copy layer" layer="sha256:4ee5c797bcd78105083ec883d8e6e8bc58124c65b30444d0110073d603e61190" source="192.168.86.78:5001/my-hello-world" target="192.168.86.31:5001/my-hello-world"
time="2021-06-25T04:31:22Z" level=info msg="Image sync needed" source="192.168.86.78:5001/my-nginx:latest" target="192.168.86.31:5001/my-nginx:latest"
time="2021-06-25T04:31:22Z" level=info msg="Copy config" digest="sha256:a2e43f88ed5333f2d0f58efdbab3e52017ee62e9802c6eab4233f65c6c7c1c29" source="192.168.86.78:5001/my-nginx" target="192.168.86.31:5001/my-nginx"
time="2021-06-25T04:31:22Z" level=info msg="Copy layer" layer="sha256:8452be1adf00f91570fe21a8e61aaf4c12e014daf67d7de65d984f4e8ecca2f1" source="192.168.86.78:5001/my-nginx" target="192.168.86.31:5001/my-nginx"
time="2021-06-25T04:31:24Z" level=info msg="Copy layer" layer="sha256:9396f7ea126c71522437f959f3adfed55b97c0d9bdd0fcfb02f1883a616c7101" source="192.168.86.78:5001/my-nginx" target="192.168.86.31:5001/my-nginx"
time="2021-06-25T04:31:27Z" level=info msg="Copy layer" layer="sha256:c4227483a2ad75396bd6075eadc176623d27ea6d926f7cbd325f3106337acb8a" source="192.168.86.78:5001/my-nginx" target="192.168.86.31:5001/my-nginx"
time="2021-06-25T04:31:27Z" level=info msg="Copy layer" layer="sha256:d7f012330c6efec2e56d3295588cde9118599c23f5d42c1cfc4211c4e849fbce" source="192.168.86.78:5001/my-nginx" target="192.168.86.31:5001/my-nginx"
time="2021-06-25T04:31:27Z" level=info msg="Copy layer" layer="sha256:9536dbb9de8f985703be12b7332fe97b5251a7a015880a956fd08a0f99717e1c" source="192.168.86.78:5001/my-nginx" target="192.168.86.31:5001/my-nginx"
time="2021-06-25T04:31:27Z" level=info msg="Copy layer" layer="sha256:d9964443b8e9c8331891e960222a7173185ad7fd689d34c0eaf9c513cff56cd9" source="192.168.86.78:5001/my-nginx" target="192.168.86.31:5001/my-nginx"
```

After completion, I confirmed that the images are now present on the target:
```
curl -s localhost:5001/v2/_catalog | jq .
{
  "repositories": [
    "my-hello-world",
    "my-nginx"
  ]
}
```

It even worked by only adding the additional image I added in the source when I ran it again.

So now I just need to run this command periodically with cron to keep the target in sync. 

Thank you!

**Comment by frakman1** [comment]
I hit a snag.
One of the repos on the source registry is malformed (or something) I don't know what's wrong with it and I couldn't delete it when I tried last time. I tried deleting it via the REST API and by deleting the folder under `/var/lib/registry/docker/registry/v2/repositories` but it still persists in the catalog as:

```
{
  "errors": [
    {
      "detail": {
        "name": "fbe"
      },
      "message": "repository name not known to registry",
      "code": "NAME_UNKNOWN"
    }
  ]
}
```

Anyway, the end result is that the regsync stops when it reaches this repo and exits. 
I there any way to have it continue and sync the rest of the repos and ignore this error?

The current error I get looks like this just before it exits.
```
time="2021-06-25T16:42:02Z" level=error msg="Failed to lookup source manifest" error="Failed to request manifest head xxxx:5000/fbe:latest: Not found [http 404]" source="xxxx:5000/fbe:latest"
Failed to request manifest head xxxx:5000/fbe:latest: Not found [http 404] 
```

**Comment by sudo-bmitch** [comment]
@frakman1 Give the latest edge release a check. It should handle bad images without stopping processing of the rest of the repos/tags. Only errors I stop on now are ones that likely indicate the rest of the attempts will fail (mainly parsing repository names which would indicate an invalid registry name was provided).

Also for scheduling this, rather than using the OS cron, there's the ability to define a cron schedule directly in the yml, and you can run the regsync with the "server" option. That keeps all the logs from multiple runs in one place. It's a good idea to have docker rotate the logs for you if you go that route. See [this old SO post for logfile rotation](https://stackoverflow.com/a/42510314/596285) and the [regsync docs](https://github.com/regclient/regclient/blob/main/docs/regsync.md) for how to define the cron schedule.

**Comment by frakman1** [comment]
Thanks. Unfortunately, I don't know how to simulate or cause an error like that again. Deleting that folder on the registry fixed the error so it was no longer an impedement.
Do you have any ideas?

**Comment by sudo-bmitch** [comment]
@frakman1 I've been known to "break" multi-platform images by deleting a single platform manifest. And it should be possible to delete a blob (though I haven't added that api to the various regclient commands) from within a pushed manifest. Either of those would break an image copy (I tested with a `regctl image copy alpine localhost:5000/alpine` + `regctl manifest rm localhost:5000/alpine@sha256...` with a single platform digest). For breaking the tag itself, I'm not sure if there's an API way to do that, perhaps something at the filesystem level did that (rm the wrong file, or a GC gone wrong).

**Comment by sudo-bmitch** [comment]
I'm going to mark this one as done. Release 0.3.5 just went out with it included. If you find an issue with registry copying, feel free to follow up here or raise a new issue. Thanks again for the suggestion!
