### ISSUE TITLE
Hi does regsync work with workload identity ?

### ISSUE THREAD

**Issue by BaskiGIT** [regclient/regclient#668]
Does regsync work with gke workload identity to sync to Google Artifact Registry ?

I am trying with regclient/regsync:alpine

<img width="933" alt="image" src="https://github.com/regclient/regclient/assets/17687380/20ba66d8-d3fd-4a25-8421-7d29338a9258">

<img width="1510" alt="image" src="https://github.com/regclient/regclient/assets/17687380/a0d9d99d-3f14-4aa9-90de-c005ff8689e3">

**Comment by BaskiGIT** [comment]
@sudo-bmitch

I tried with the config in the initial image of the Question after uncommenting credHelper.

But without mounting service account token I cannot get regsync to authenticate to GAR ( Google Artifact Registry )

What works though is the below :

1. Create the pod with `command: ["/bin/sh"]` and `args: ["-c", "while true; do date; echo sleeping for 600s; sleep 600; done"]`
2. Create a service account key of the GCP IAM service account in GCP console
3. Mount the sa key inside the pod at home/appuser/.config/gcloud/application_default_credentials.json
4. Execute `docker-credential-gcr configure-docker --registries=europe-docker.pkg.dev` in the pod
5. Execute `regsync once -c /etc/regsync/regsync.yml -v debug`

`docker-credential-gcr configure-docker --registries=europe-docker.pkg.dev` is not executed by the command `regsync once -c /etc/regsync/resync.yml -v debug`

Did you manage to get it working previously using GKE workload identity ( without having to create a key for GCP service account ) ?

**Comment by sudo-bmitch** [comment]
The readme on docker-credential-gcr seems to indicate they require a service account, which would need to be associated with the container. If it has access, you should be able to run the following to get a token:

```shell
echo "europe-docker.pkg.dev" | docker-credential-gcr get
```

I don't have access to GKE myself, so best I can do it refer you to guides for the credential helper:

- https://cloud.google.com/artifact-registry/docs/docker/authentication#standalone-helper
- https://cloud.google.com/docs/authentication#service-accounts
- https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

If those don't work and the credential helper still isn't returning a working token, then either the GKE or the credential helper maintainers would probably be a better resource. Once you have a working token from the helper running in the container, if that doesn't work with regsync, I can try to assist further.

**Comment by BaskiGIT** [comment]
@sudo-bmitch :

Okay so workload identity support is not yet possible for regsync to connect to GAR ( workload identity is a secure way to connect to GCP instead of using service account keys which pose a security risk ). So if you could add the support to workload identity as a feature to regsync it would help those who use GAR as their container registry.

However there is still a concern with regsync by using service account key.

1. Mount service account in the pod at `home/appuser/.config/gcloud/application_default_credentials.json` and run it in GKE
2. Execute `regsync once -c /etc/regsync/regsync.yml -v debug`

The above 2 steps do not succeed.

Have to add an additional manual step to configure credHelper.

1. Mount service account in the pod at `home/appuser/.config/gcloud/application_default_credentials.json` and run it in GKE
2. Execute `docker-credential-gcr configure-docker --registries=europe-docker.pkg.dev`
3. Execute `regsync once -c /etc/regsync/regsync.yml -v debug`

With these 3 steps ( additional step to configure credHelper ), regsync works.

When `credHelper: docker-credential-gcr` is set in `/etc/regsync/regsync.yml` the manual execution of configuring credential helper should not be required right ?

`credHelper: docker-credential-gcr` is supposed to configure credential helper right ?

**Comment by sudo-bmitch** [comment]
For issues with docker-credential-gcr, please report those in their own GitHub repo: https://github.com/GoogleCloudPlatform/docker-credential-gcr

regclient calls credential helpers using their predefined spec, which is to run `$helper get` and pass the hostname to stdin. It does not implement any of the helper logic itself, it only includes two of the more popular ones in the alpine images for convenience.

**Comment by sudo-bmitch** [comment]
The configure-docker command is used to setup a config.json file used by docker logins, and regsync will fallback to that if the credentials are not setup correctly in the yml file. The screenshot is difficult to read and apparently not the one you are using, but make sure you have configured the registry option on the entry with the credential helper, and skip setting the hostname value (the uses for that are rare).

**Comment by BaskiGIT** [comment]
@sudo-bmitch okay now with `registry` instead of `hostname` I can have regsync do the work without having to explicitly execute `docker-credential-gcr configure-docker --registries=europe-docker.pkg.dev`

We can conclude this issue/thread

Ending notes :

- regsync does not work with GKE workload identity
- regsync works syncing to GAR with gcp service account credentials mounted in the pod
