### ISSUE TITLE
"use of closed network connection" on long-lived blob pushes (how can I configure timeouts?)

### ISSUE THREAD

**Issue by zaneclaes** [regclient/regclient#69]
I have been attempting to use `regctl image copy`, per @sudo-bmitch 's advice on [this StackOverflow question](https://stackoverflow.com/questions/68317302/is-it-possible-to-copy-a-multi-os-image-from-one-docker-registry-to-another-on-a).  Unfortunately, it hasn't worked with any of the repositories or images I've tried so far, due to the following error:

```
Failed to send blob (put), digest sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d, ref docker.io/openworkshop/maker-builder@sha256:9cc2c46e51c9d14e287bddb3033c4217864f5662a01a70c2153ecbc699e376a0: Put "https://registry-1.docker.io/v2/openworkshop/maker-builder/blobs/uploads/66a6c3c2-b0df-494b-965a-8eb5b6b09c3b?_state=8z14zK0MmvI0dTyAh47nrgpfvlH1yJXdKFyN_9Kkj117Ik5hbWUiOiJvcGVud29ya3Nob3AvbWFrZXItYnVpbGRlciIsIlVVSUQiOiI2NmE2YzNjMi1iMGRmLTQ5NGItOTY1YS04ZWI1YjZiMDljM2IiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMDctMTJUMTQ6MDU6NDAuMDI3MzA3MDQ3WiJ9&digest=sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d": write tcp 10.244.5.46:58970->54.161.109.204:443: use of closed network connection
--
  |  
  | at ChildProcess.exithandler (node:child_process:397:12)
  | at ChildProcess.emit (node:events:394:28)
  | at maybeClose (node:internal/child_process:1067:16)
  | at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  | killed: false,
  | code: 1,
  | signal: null,
  | cmd: 'regctl image copy -v info containers.oodalolly.camp/openworkshop/maker-builder:latest docker.io/openworkshop/maker-builder:latest'
  | }
```

This is likely due to the fact that (1) layers in my windows server images are multiple GB in size and (2) my internet connection is poor.

I have tried searching this repository for `timeout` related options, as well as looked at the MAN (`regctl image copy —help`) and registry config source code. AFAICT, there is no way to pass in the necessary timeout flags to regctl (?)

**Comment by sudo-bmitch** [comment]
Thanks for the report. I think there's more I can do to improve fault tolerance with unstable networks, and in particular retrying a blob send after a previous failure. The regctl command itself doesn't have a timeout. One could be added but I don't believe that would help here. Instead it stops on an error, including a network fault, or user interruption (cont-c).

For additional debugging, output with `-v debug` would help, along with an indication of whether the error happens at the same place in every blob.

**Comment by zaneclaes** [comment]
Hm. I don't use golang myself, but [some research indicates](https://stackoverflow.com/questions/31385487/golang-http-having-use-of-closed-network-connection-error) that this is a standard "connection closed before content length headers received" sort of error. Broadening the search to other languages, then, it seems [specific to the Docker API as it pertains to Windows images](https://github.com/docker/for-win/issues/611). I'm not using a proxy, but I am attempting to push the image from within a Docker container (my CI itself is dockerized), though the container is based upon `debian-slim` and running on an Ubuntu host.

The issue always happens with the same blob. Here's a paste of the debug logs:

```

INFO[0019] Copy layer                                    layer="sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d" source="containers.oodalolly.camp/openworkshop/maker-builder:latest" target="docker.io/openworkshop/maker-builder:latest"
DEBU[0019] Sending request                               method=HEAD url="https://registry-1.docker.io/v2/openworkshop/maker-builder/blobs/sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d" withAuth=true
DEBU[0020] Not found                                     Status="404 Not Found" URL="https://registry-1.docker.io/v2/openworkshop/maker-builder/blobs/sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d"
DEBU[0020] Sending request                               method=GET url="http://containers.oodalolly.camp/v2/openworkshop/maker-builder/blobs/sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d" withAuth=false
DEBU[0020] Auth scope added                              host=registry-1.docker.io scope="repository:openworkshop/maker-builder:pull,push"
DEBU[0022] Sending request                               method=POST url="https://registry-1.docker.io/v2/openworkshop/maker-builder/blobs/uploads/?mount=sha256%3A0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d" withAuth=true
DEBU[0025] Sending request                               method=PUT url="https://registry-1.docker.io/v2/openworkshop/maker-builder/blobs/uploads/8594ad96-588f-4bec-bc15-85588f94c5e1?_state=SaoITkccZf_dtBIO50qojZLYnjAG6aYY6PiRaMkvuLN7Ik5hbWUiOiJvcGVud29ya3Nob3AvbWFrZXItYnVpbGRlciIsIlVVSUQiOiI4NTk0YWQ5Ni01ODhmLTRiZWMtYmMxNS04NTU4OGY5NGM1ZTEiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMDctMTJUMTc6NTg6MDAuMzMyODgyOTc5WiJ9&digest=sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d" withAuth=true
aDEBU[3292] Unexpected status                             Status="504 Gateway Time-out" URL="https://registry-1.docker.io/v2/openworkshop/maker-builder/blobs/uploads/8594ad96-588f-4bec-bc15-85588f94c5e1?_state=SaoITkccZf_dtBIO50qojZLYnjAG6aYY6PiRaMkvuLN7Ik5hbWUiOiJvcGVud29ya3Nob3AvbWFrZXItYnVpbGRlciIsIlVVSUQiOiI4NTk0YWQ5Ni01ODhmLTRiZWMtYmMxNS04NTU4OGY5NGM1ZTEiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMDctMTJUMTc6NTg6MDAuMzMyODgyOTc5WiJ9&digest=sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d"
WARN[3292] Failed to push blob                           err="Failed to send blob (put), digest sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d, ref docker.io/openworkshop/maker-builder@sha256:9cc2c46e51c9d14e287bddb3033c4217864f5662a01a70c2153ecbc699e376a0: All requests failed" src="containers.oodalolly.camp/openworkshop/maker-builder:latest" tgt="docker.io/openworkshop/maker-builder:latest"
WARN[3292] Failed to copy layer                          err="Failed to send blob (put), digest sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d, ref docker.io/openworkshop/maker-builder@sha256:9cc2c46e51c9d14e287bddb3033c4217864f5662a01a70c2153ecbc699e376a0: All requests failed" layer="sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d" source="containers.oodalolly.camp/openworkshop/maker-builder:latest" target="docker.io/openworkshop/maker-builder:latest"
Failed to send blob (put), digest sha256:0e7c9a9df090dca82298fa849f9b5b7886a552cfac13077f625f8a95bf3b192d, ref docker.io/openworkshop/maker-builder@sha256:9cc2c46e51c9d14e287bddb3033c4217864f5662a01a70c2153ecbc699e376a0: All requests failed
root@buildkite-agent-amd64-7:/# 

```

**Comment by sudo-bmitch** [comment]
From the earlier edit, I saw there was a `Status="504 Gateway Time-out"`. If that's not coming from a local proxy, it could be part of the Docker Hub infrastructure itself, so I wouldn't read too much into it. The big telling part to me is how much time the logs indicated had passed, which appeared to be about 55 minutes, so my expectation is the request is well past sending headers. My best guess is something server side killing connections that are up for over 50 minutes.

Adding some retry logic, and falling back to chunked uploads should make a big improvement here, so I'll make that the next priority for this project.

**Comment by sudo-bmitch** [comment]
@zaneclaes have a look at `regclient/regsync:edge` or `regclient/regsync:alpine-edge` to see if they resolve this for you. The retry code wasn't too difficult to add, but finally getting around to writing some decent test code took a bit of effort. Hopefully that pays off with fewer bugs and regressions in the future.

**Comment by sudo-bmitch** [comment]
[Release v0.3.6](https://github.com/regclient/regclient/releases/tag/v0.3.6) just went out with #70 which will hopefully resolve this.
