### ISSUE TITLE
[Feature] Inspect in public API

### ISSUE THREAD

**Issue by drev74** [regclient/regclient#704]
### Current Behavior

Thanks for building this incredibly useful software! :smiley: I use it as a client library in my `cli` and need to implement `oci/docker image inspect`. Currently, image `inspection` is buried in your code and I used [this](https://github.com/regclient/regclient/blob/1eccd0755c352e37e56a170917857e6dd5711985/cmd/regctl/image.go#L1326) as a reference.

### Expected Behavior

Need to have a proper `image inspect` as a public API

### Version

```text
v0.6.0
```

### Environment

- Running as binary or container: using a go library
- Host platform: Ubuntu amd64
- Registry description: registry:3-alpha1

**Comment by sudo-bmitch** [comment]
Thanks for the suggestion. I've got this on my todo list. It's a bit buried since the underlying process is several API's to get the specific blob and parse it. But, similar to `ImageCopy`, `ImageExport`, and `ImageImport`, adding an `ImageInspect` makes sense.

**Comment by sudo-bmitch** [comment]
Thanks again for the suggestion. This should be fixed in #706. Let me know if you encounter any issues.
