### ISSUE TITLE
[Question] Interest in depending on regclient 

### ISSUE THREAD

**Issue by thesayyn** [regclient/regclient#712]
### Background

We are designing the 2.0 version of rules_oci so i have been looking for a could replace crane but knows how to work on ocidirs.

The new design has these requirements;

- [x] Can work directly on oci directories 
- [x] Can be downloaded as a static binary.
- [ ] Has an relatively stable cli surface (not sure about this)

The main motivation for us to not have an ephemeral registry running for each build task. I have came across regctl couple times but never considered it as tool that can be used for assembling container images like [stacker](https://github.com/project-stacker/stacker). We are also considering stacker FWIW.

### Question

- Do you it's okay to use regctl for image building purposes, eg by combining `regctl blob put < blob && regctl manifest put`?
- How would you feel about rules_oci using regctl? We might send new feature requests or people might increasingly report issues here. Would that be overwhelming for the maintainers here?

**Comment by sudo-bmitch** [comment]
Hi @thesayyn. The CLI for those commands is "relatively stable". I assume that they would be used in shell scripts by now and avoid making any changes that would break that CLI. The version is less than 1.0 mainly to keep the freedom to update the underlying Go API, but even those changes tend to go through a deprecation cycle for a few minor releases when possible.

**Comment by thesayyn** [comment]
> I assume that they would be used in shell scripts by now and avoid making any changes that would break that CLI.
That's a reasonable assumption. How about other points?  depending on regclient in rules_oci might lead to more issues being reported here. 
I can pitch in time to time to contribute patches myself.

**Comment by sudo-bmitch** [comment]
I'm happy to see more issues if it means this can become a better project. Issues and PRs are welcome!

**Comment by thesayyn** [comment]
Just for visibility: My proposal to change rules_oci to use regclient got approved. A lot more downloads of regclient!

https://docs.google.com/document/d/1wZEB9QFxyrydhLiafYbaJ0D7Jd2FZRZjvoTtx0B8-yY

**Comment by sudo-bmitch** [comment]
Very nice! That's also useful to understand the context of the other requests. I'm going to close this issue since I believe everything here has been answered, but feel free to keep the conversation going here or open another issue if there's anything else you need.
