### ISSUE TITLE
Add support for ppc64le and s390 archtectures.

### ISSUE THREAD

**Issue by rpsene** [regclient/regclient#72]
This is a feature request to start providing binaries for ppc64le and s390x. This can be either a cross-compilation OR a Travis-CI integration, given that Travis supports all available architectures natively.

**Comment by sudo-bmitch** [comment]
The cross-compile looks like it's working for these in container images in my local environment. I'll update the CI later on to get some edge builds out and cut a release in another day or two.

**Comment by sudo-bmitch** [comment]
@rpsene have a look at the artifacts included in the latest GHA run: https://github.com/regclient/regclient/actions/runs/1118022705

Assuming those look good, I'll cut a new release in the next few days so they're easier to download.

**Comment by sudo-bmitch** [comment]
[Release v0.3.6](https://github.com/regclient/regclient/releases/tag/v0.3.6) just went out with #74 which should resolve this. Thanks for the request!
