### ISSUE TITLE
[Feature] Adding new layers to existing image

### ISSUE THREAD

**Issue by thesayyn** [regclient/regclient#721]
### Current Behavior

Looks like regctl does not support adding new layers to existing images, other than simply supporting pushing blobs to registry/ocidir. 

### Expected Behavior

I was not expecting regctl to do anything here, as it provides primitive commands to accomplish this but it hard to use as one needs to know exactly how container images are assembled. 

### Example Solution

I am proposing two new flags to `regctl image mod` that supports; (naming TBD)

1. Adding a new layer where rest is done by `regctl`

Example:  `regctl image mod  --layer-add path/to/tar`

This does everything: calculates diffid, digest and size and modifies config and manifest of the given image. 

2. Adding a layer where diffid and digest is precalculated

Example: `regctl image mod  --layer-add-with diffid=digest=path/to/tar`

This the same thing as above except calculating the diffid and digest is done by external tooling ahead of time and provided directly. 

I am mostly interested in the second flag, as it would benefit [rules_oci](https://github.com/bazel-contrib/rules_oci)

### Version

```text
VCSTag:     v0.6.0
VCSRef:     9de7397da9f1c00dad5213519366002376b8d5ed
VCSCommit:  9de7397da9f1c00dad5213519366002376b8d5ed
VCSState:   clean
VCSDate:    2024-03-24T18:09:00Z
Platform:   darwin/arm64
GoVer:      go1.22.1
GoCompiler: gc
```

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

**Comment by sudo-bmitch** [comment]
#736 solves the request for the first option. I have concerns about including the ability to do the second option, since the compression type could mismatch the media type, and it requires a lot of trust on the end users to know the difference between the digest in the config and the digest of the blob (from my experience, very few people know that).
