### ISSUE TITLE
[Feature] Support for creating new images that contain nothing

### ISSUE THREAD

**Issue by thesayyn** [regclient/regclient#722]
### Current Behavior

AFAICT regctl has no command that can create an empty image, eg: `FROM scratch`

### Expected Behavior

None

### Example Solution

I am proposing adding a new subcommand named `regctl image create` that will create an empty image and push it a registry/ocidir.

Example: `regctl image create <REF> --os linux --arch arm64 --variant v8`

### Version

```text
VCSTag:     v0.6.0
VCSRef:     9de7397da9f1c00dad5213519366002376b8d5ed
VCSCommit:  9de7397da9f1c00dad5213519366002376b8d5ed
VCSState:   clean
VCSDate:    2024-03-24T18:09:00Z
Platform:   darwin/arm64
GoVer:      go1.22.1
GoCompiler: gc
```

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

**Comment by thesayyn** [comment]
The primitive way to do this is:

```bash
config_digest=$(regctl blob put ocidir://tools/regctl/output:latest <<EOF
{
   "created": "",
   "architecture": "arm64",
   "os": "linux",
   "variant": "v8",
   "config": {},
   "history": [],
   "rootfs": {
      "type":"layers",
      "diff_ids": []
   }
}
EOF
)

regctl manifest put ocidir://tools/regctl/output:latest <<EOF
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.manifest.v1+json",
   "config": {
      "mediaType": "application/vnd.oci.image.config.v1+json",
      "digest": "$config_digest" 
   },
   "layers": []
}
EOF

```

**Comment by sudo-bmitch** [comment]
Thanks for the suggestion! That would align fairly well with `regctl index create`. I've added it to my todo list.

**Comment by sudo-bmitch** [comment]
This should now be supported. I have intentions to extend this with the option to include layers in the future, avoiding the need to mod the image after it is created.
