### ISSUE TITLE
[Feature] Support slog

### ISSUE THREAD

**Issue by Snaipe** [regclient/regclient#749]
### Current Behavior

Structured logging has now been standardized in the `log/slog` package. API consumers that use slog need to allocate a separate logrus logger to use with regclient, which is fairly inconvenient.

### Expected Behavior

There should be an Opt to specify the slog.Logger to use.

### Example Solution

Fixing this would mean:

1. Internally convert all uses of logrus to an slog Logger instead
2. A new option function would be implemented:

  ```go
  func WithSLog(log *slog.Logger) Opt
  ```
3. For compatibility, `WithLog` would create a new slog.Logger and wrap the logrus Logger as its slog.Handler, then pass it to WithSLog.

**Comment by sudo-bmitch** [comment]
regclient maintains support for at least 3 releases of Go, which means 1.20 - 1.22 right now. This would need to wait until 1.23 is released and 1.20 support is dropped.

**Comment by shanduur** [comment]
What about moving to [logr](https://github.com/go-logr/logr)?

**Comment by Snaipe** [comment]
The main difference is that slog is part of the standard library, while logr isn't -- not because it's bad, but because it precedes slog. It doesn't seem compelling to add more alternate logging interfaces when consolidating existing code to start using the standard library more seems like a somewhat obvious path forward.

**Comment by sudo-bmitch** [comment]
In addition to removing dependencies by shifting to the standard library in the future, it's a bit unusual for an application to tightly bind its logging to that of the libraries that it uses. A majority of users would leave logging completely disabled (the default) and just check the error responses. In a shift to slog I'm expecting to remove a number of logging points, and focus on http tracing that may be needed to debug low level issues.

**Comment by ydnar** [comment]
Just got bit by the `logrus` dependency using this module (thanks!) with `GOOS=wasip1`. Now that Go 1.23 is released, would you consider dropping the `logrus` dependency?

**Comment by sudo-bmitch** [comment]
Adding log/slog support is definitely on the list. Deprecating logrus will take time since people need the opportunity to upgrade their own tools without immediate breaking changes.

**Comment by ydnar** [comment]
Thanks! We've currently implemented a workaround where the regclient dependency is only in non-WASI builds.

**Comment by ydnar** [comment]
Thanks!

We use regclient to fetch OCI artifacts containing WebAssembly components: https://pkg.go.dev/go.bytecodealliance.org
