### ISSUE TITLE
[Question] Is it possible to let regsync sync the latest 10 images only?

### ISSUE THREAD

**Issue by BrettDean** [regclient/regclient#761]
### Question

If it's a very old repository, there are too many images, which would require significant space and time to sync. 

Especially considering that hardly anyone uses the earliest images. 

I'd like to inquire if it's possible for regsync to only sync the latest 10 images. Thanks.

### Version

```
VCSTag:     v0.6.1
VCSRef:     766ee6291f882778207ff42207f9ca8b1da54e57
VCSCommit:  766ee6291f882778207ff42207f9ca8b1da54e57
VCSState:   clean
VCSDate:    2024-05-14T13:18:19Z
Platform:   linux/amd64
GoVer:      go1.22.3
GoCompiler: gc
```
### Environment

- Running as binary or container:`binary `
- Host platform:`Linux `
- Registry description:`registry:2.8.2`

### Anything else

`NONE`

**Comment by sudo-bmitch** [comment]
At present, regsync cannot do this, but a regbot script could be written to implement it. Part of the complication is that different repositories have different tag naming schemes, so knowing which tags are the latest requires additional knowledge about the repository.
