### ISSUE TITLE
[Issue] Returning a wrong label value

### ISSUE THREAD

**Issue by tcurdt** [regclient/regclient#764]
### Current Behavior

I am using `regclient` to resolve labels of OCI images

https://github.com/tcurdt/oci-resolve/blob/main/resolve.go#L140

and this works - but I ran into a weird problem. I am checking for two labels:

```
	sha := or(
		imageConfig.Config.Labels["org.opencontainers.image.revision"],
		imageConfig.Config.Labels["SHA"],
	)
```

and pick whichever exists. Now I had an image with **only** the `SHA` label set.
Yet, `org.opencontainers.image.revision` was returning a (different and unexpected) value. 🤔

### Expected Behavior

`imageConfig.Config.Labels["none-existant-label"]` should return "".

### Steps To Reproduce

1. clone https://github.com/tcurdt/oci-resolve/tree/v0.0.12
2. modify the image name in https://github.com/tcurdt/oci-resolve/blob/main/in/echo1.yaml to point something you have can control over and want to check
3. run `go run ./... transform in` (or pass a registry credentials file with `-r`)

### Version

```text
github.com/regclient/regclient v0.6.1
```

### Environment

Tested on arm64/Mac and amd64/Linux.
Inside a container and outside.
Registry was ghcr.io

**Comment by tcurdt** [comment]
When I also add the `org.opencontainers.image.revision` label all works as expected.

**Comment by sudo-bmitch** [comment]
Can you provide a failing unit test for this?

**Comment by tcurdt** [comment]
I am off for vacation tomorrow. So it will take a bit. But I will try to make it easier to reproduce after.

**Comment by tcurdt** [comment]
Back from vacation but still a bit unsure how to make this reproducible via test.

I assume it should go here?

https://github.com/regclient/regclient/blob/main/manifest_test.go

**Comment by sudo-bmitch** [comment]
I was thinking along the lines of a `github.com/tcurdt/oci-resolve/blob/main/resolve_test.go` to show the issue you are experiencing since the steps provided above had a lot of ambiguity.
