### ISSUE TITLE
[Question] How to push an image to registry

### ISSUE THREAD

**Issue by mojixcoder** [regclient/regclient#781]
Hello all,
I wanted to know how can I push a local image to an image registry? To be precise, equivalent of `docker push` with `regctl`.
Here is the help output of `regctl image --help`:
```
Usage:
  regctl image [command]

Available Commands:
  check-base  check if the base image has changed
  copy        copy or retag image
  create      create a new image manifest
  delete      delete image, same as "manifest delete"
  digest      show digest for pinning, same as "manifest digest"
  export      export image
  get-file    get a file from an image
  import      import image
  inspect     inspect image
  manifest    show manifest or manifest list, same as "manifest get"
  mod         modify an image
  ratelimit   show the current rate limit
```

**Comment by sudo-bmitch** [comment]
That would either be a `regctl copy` command or `regctl import` depending on where the image is currently located. If it's on a local registry, or output to a OCI Layout in directory format, you would `regctl image copy`. If the image is in something like the docker engine, you'd need to first `docker save` that image to their tar file, and then `regctl image import` to a registry. `regctl` is for interfacing with OCI registries, so it won't talk directly to docker or podman.

**Comment by mojixcoder** [comment]
Thanks for your response.
