### ISSUE TITLE
[Feature] regctl supports concurrent import images？

### ISSUE THREAD

**Issue by comqx** [regclient/regclient#785]
exp: 
regctl image import -v debug  mysql:5.7  mysql-new.tar  

Whether concurrent import is supported. Or is it currently a single request? That is, layer by layer to request import into the warehouse

**Comment by sudo-bmitch** [comment]
Because of the design of `regctl image import`, it only works on a single layer at a time. Using an `ocidir` for the source, rather than the tar file, would allow for `regctl image copy` to work with concurrency.
