### ISSUE TITLE
[Feature] Wasm: support `application/vnd.wasm.config.v0+json` media type

### ISSUE THREAD

**Issue by Mossaka** [regclient/regclient#791]
### Current Behavior

```bash
> docker pull ghcr.io/webassembly/wasi/http:0.2.0
0.2.0: Pulling from webassembly/wasi/http
Digest: sha256:b292aade5066edbbd860b0c87180085a813121c61103702ecd09772a4c03283a
Status: Downloaded newer image for ghcr.io/webassembly/wasi/http:0.2.0
ghcr.io/webassembly/wasi/http:0.2.0

> regctl image inspect ghcr.io/webassembly/wasi/http:0.2.0                                      
unsupported config media type application/vnd.wasm.config.v0+json: unsupported media type
```

### Expected Behavior

regctl should be able to inspect the wasm image.

### Version

```text
(paste output of `regctl version` or similar for binaries, or `docker image inspect regclient/...` on the image and paste the labels)
```

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

### Anything else

The wasm meida type is standardized by the CNCF WebAssembly Working Group. Please see this for detail:
https://tag-runtime.cncf.io/wgs/wasm/deliverables/wasm-oci-artifact/

**Comment by sudo-bmitch** [comment]
The `regctl image inspect` command is designed for OCI (and Docker) container images. For artifacts like WASM images, the tooling for that is much better handled with `regctl artifact get`. I've added the `--config` flag to make that workflow easier.
