### ISSUE TITLE
[Issue] Sync to (private) Azure Container Registry produces Request Header Or Cookie Too Large Error

### ISSUE THREAD

**Issue by jonas-budde** [regclient/regclient#797]
### Current Behavior

In my current project im using regsync in an k8s cluster to sync from an quay registry to a private Azure Container Registry. 
I use a Config Map to configure regsync and a init container to create the .docker/config.json.

My Error:
`
{"error":"failed to list tags for myprivateacr.azurecr.io/services/company/service-name-xy:latest: request failed: unexpected http status code: Bad Request [http 400]: \u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e400 Request Header Or Cookie Too Large\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody bgcolor=\"white\"\u003e\r\n\u003ccenter\u003e\u003ch1\u003e400 Bad Request\u003c/h1\u003e\u003c/center\u003e\r\n\u003ccenter\u003eRequest Header Or Cookie Too Large\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003eAzureContainerRegistry\u003c/center\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e\r\n","level":"debug","msg":"Failed getting target tags","target":"myprivateacr.azurecr.io/services/company/service-name-xy:latest","time":"2024-07-31T10:10:32Z"}
`

Why does regsync produces this error? 
I filtered for only images which don't have the latest tag and also just want linux/amd64 images.

This is my current config:
<details>
<code>
version: 1
defaults:
  interval: 1m
sync:
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
  - source: private-quay.company.com/mynamespace/service-name-xy
    target: myprivateacr.azurecr.io/services/company/service-name-xy
    type: repository
    platform: linux/amd64
    tags: 
      deny:
      - "^latest.*"
</code>
</details>

### What I tried
- removing the platform option
- removing the tag option
- setting parallel, fastCopy, cacheTime and cacheCount

### Expected Behavior

All ~35 Repositories should sync to the target registry. 

### Version

Docker Container Version: 0.7.0

### Environment

- Kubernetes (Azure Linux Nodes)
- Source Registry: self-hosted quay
- Target Registry: ACR

**Comment by sudo-bmitch** [comment]
The tag listing error indicates something wrong with the API access to the registry. I don't currently have an ACR login to debug their registry myself. There are various commands that can be tried to debug that API:

```shell
# make sure regctl from regclient also fails:
regctl tag ls -v debug myprivateacr.azurecr.io/services/company/service-name-xy

# check if other tools work, crane is from google/go-containerregistry and ORAS is a CNCF project managed by Microsoft
crane ls myprivateacr.azurecr.io/services/company/service-name-xy
oras repo tags myprivateacr.azurecr.io/services/company/service-name-xy
```

regclient doesn't add many headers to a request, the main one I'm thinking of is the auth header, and the content for that comes from the registry. If it is that auth header, then the first thing I'd try is switching to an auth header per repository with:

```yaml
creds:
  - registry: "private-quay.company.com"
    repoAuth: true
```

**Comment by jonas-budde** [comment]
The regctl command produced no errors.
The "repoAuth" option was a solution to my problem! I think it caused this problem, because there where so many simultaneously requests with the same token.
In my opinion the documentation is a bit unclear on if you are able to use the creds section when using regsync in server mode. I understood it like everything is sourced from .docker/config.json and the whole creds section is ignored.

Thank you for helping so quickly and for developing this tool! 😊
