### ISSUE TITLE
[Question] Nested index: is it normal for an index to be deleted if its tag is deleted even when it is part of another index

### ISSUE THREAD

**Issue by Sebastian-Maier** [regclient/regclient#808]
### Question

I want to copy a multi-platform image (index) to a repository (via `regctl image copy`) and include its digest as an platform-independent entry in another multi-platform image (index) that I add to the same repository.
Since I do no longer need (nor want) a specific tag referencing the copied image, I delete it with `regctl tag delete`.
All these operations succeed. However when I try to access/retrieve the image copied originally (via the digest stored in the root index), the image is no longer available.

Is this normal behavior even when the image/index is still referenced (via digest in the root index)?
Is this a `regctl` or an OCI registry issue? (I use ZOT v2.1.1 for testing.)
Is there a way to copy a multi-platform image (index) with `regctl` without a specific target tag?

### Version

```text
VCSTag:     0.7.1
VCSRef:     unknown
VCSCommit:  unknown
VCSState:   unknown
VCSDate:    unknown
Platform:   darwin/arm64
GoVer:      go1.22.5
GoCompiler: gc
```

### Environment

- Running as binary or container: downloaded binary
- Host platform: Mac
- Registry description: ZOT (v2.1.1)

**Comment by sudo-bmitch** [comment]
This may be more of a Zot question. In general, you're in uncharted territory since garbage collection is not specified by the OCI specs and a nested index is permitted but not mandated for registries to support (it's listed under the "SHOULD" part of the spec).

To start debugging, I'd need a complete list of commands you are running. It would also be useful to include `regctl tag ls` on the repo, and `regctl manifest get` on both indexes, before the `regctl tag rm`.

**Comment by Sebastian-Maier** [comment]
I was already in contact with the ZOT maintainers and it seems to be a ZOT issue:
[ZOT Issue 2624](https://github.com/project-zot/zot/issues/2624)

In turn, we can probably close this question.
However, I am still wondering whether it wouldn't make sense to have an option to copy an image/index via `regctl image copy` only by digest and without specifying a target tag (e.g., to allow for the construction of a nested index). But I am not sure whether this is supported or intended by the OCI spec.
Anyway, if I try to construct such a nested index by deleting the (temporary) tag after constructing the root index, I can always end up with an unwanted/confusing tag (and an unused image/index as it is still referenced by the tag) for example when the script fails or something goes wrong while finishing the creation of the root index or the deletion of the temporary tag. In addition, the tag is temporarily visible to everyone (which might not always be desirable).

**Comment by sudo-bmitch** [comment]
The `regctl image copy` command supports copying by digest. The syntax for a digest at the end of a reference is `@sha:1234...` rather than `:tag`.

**Comment by Sebastian-Maier** [comment]
> The `regctl image copy` command supports copying by digest. The syntax for a digest at the end of a reference is `@sha:1234...` rather than `:tag`.

Oh I didn't know that. Thank you for the information. 
I will close this question then.
