### ISSUE TITLE
[Feature] regctl manifest diff should have return codes like "regular diff"

### ISSUE THREAD

**Issue by jpommerening** [regclient/regclient#825]
### Current Behavior

Currently, `regctl manifest diff` returns "1" if an error occurred and "0" in all other cases:

```shell
> regctl manifest diff regclient/regctl:v0.7.0 regclient/regctl:v0.7.0
> echo $?
0
> regctl manifest diff regclient/regctl:v0.7.0 regclient/regctl:v0.7.1
... [diff] ...
> echo $?
0
> regctl manifest diff regclient/regctl:v0.7.0 regclient/regctl:v999.999.999
failed to get manifest docker.io/regclient/regctl:v999.999.999: request failed: not found [http 404]: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":"unknown tag=v999.999.999"}]}

> echo $?
1
```

### Expected Behavior

It would be nice if `regctl manifest diff` behaved more like traditional `diff` or `kubectl diff` (or `git diff`) and used the return code to report if there were differences.

This would make the command more useful in scripts where a user just wants to check _if_ there are differences between manifests, but is not interested in the actual differences.

To make this change backwards compatible the behavior could be enabled via a command line switch (like is done with git):

```shell
> regctl manifest diff --quiet regclient/regctl:v0.7.0 regclient/regctl:v0.7.1
> echo $?
1
```

From `man diff`:

>     EXIT STATUS
>         The diff utility exits with one of the following values:
>
>            0       No differences were found.
>            1       Differences were found.
>            >1      An error occurred.
>
>         The --help and --version options exit with a status of 0.

From `man kubectl-diff`:

>     Exit status: 0 No differences were found. 1 Differences were found. >1 Kubectl or diff failed with an error.

From `man git-diff`:

>     --exit-code
>         Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.
>
>     --quiet
>         Disable all output of the program. Implies --exit-code.

### Version

```text
VCSTag:     0.6.1
VCSRef:     unknown
VCSCommit:  unknown
VCSState:   unknown
VCSDate:    unknown
Platform:   darwin/arm64
GoVer:      go1.22.3
GoCompiler: gc
```

### Environment

- Running as binary or container: binary
- Host platform: macOS
- Registry description: `brew install regclient`

### Anything else

Thank you for building and sharing this great tool! It improved my workflow a lot :heart:

**Comment by sudo-bmitch** [comment]
Are you only interested in whether the manifest has changed, or do you also want to see the differences if there are changes? Because a digest comparison is much better for the former.
