### ISSUE TITLE
[Feature] A `regctl` option to remove an environment variable

### ISSUE THREAD

**Issue by markshep-wbg** [regclient/regclient#864]
### Current Behavior

With the `regctl image mod` command there are currently options to remove exposes and build args.

### Expected Behavior

I'd like there to also be an option to remove an environment variable.

### Example Solution

`regctl image mod --env-rm NAME=value ...`

### Version

```text
VCSTag:     v0.7.2
VCSRef:     6b1f7bd9a3b2972605f04a534143f7fed522b680
VCSCommit:  6b1f7bd9a3b2972605f04a534143f7fed522b680
VCSState:   clean
VCSDate:    2024-11-04T14:37:25Z
Platform:   darwin/arm64
GoVer:      go1.23.2
GoCompiler: gc
```

### Environment

- Running as binary or container:
    - Downloaded binary from GitHub releases page
- Host platform:
    - Mac ARM
- Registry description:
    - Copied an image from Docker Hub to an ocidir then modifying that

**Comment by sudo-bmitch** [comment]
Thank you for the suggestion. #867 should resolve this. If you experience any issues with it, let me know and we can reopen this.
