### ISSUE TITLE
[Issue] platform_test is failing on macOS darwin/amd64

### ISSUE THREAD

**Issue by XA21X** [regclient/regclient#876]
Possible regression from #782.

### Current Behavior

```
ok      github.com/regclient/regclient/types/mediatype  6.842s  coverage: 100.0% of statements
--- FAIL: TestPlatformParse (0.00s)
    --- FAIL: TestPlatformParse/macos_amd64 (0.00s)
        platform_test.go:192: platform did not match, want darwin/amd64/v3, received darwin/amd64
FAIL
coverage: 84.1% of statements
FAIL    github.com/regclient/regclient/types/platform   6.729s
```

### Expected Behavior

The test should pass, and the make command should succeed.

### Steps To Reproduce

Build regclient using official instructions. Clone and make.

### Version

`0.7.2`

### Environment

- Running as binary or container: N/A, test failure.
- Host platform: `Darwin Kernel Version 23.6.0: Thu Sep 12 23:34:49 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_X86_64`
- Registry description: N/A

**Comment by sudo-bmitch** [comment]
Thank you for the report @XA21X. I don't have a Mac to test on, so if you have a chance, give #879 a try.

**Comment by XA21X** [comment]
Thanks for the quick fix. I've successfully built and tested it on both my amd64 and aarch64 MacBooks.

```
ok      github.com/regclient/regclient/types/platform   1.027s
```

**Comment by sudo-bmitch** [comment]
> Thanks for the quick fix. I've successfully built and tested it on both my amd64 and aarch64 MacBooks.

Perfect! This should get released in a week or so, there's just a bit more work on a new feature left to finish.
