### ISSUE TITLE
[Question] Push a blob using regclient as a library

### ISSUE THREAD

**Issue by Skarlso** [regclient/regclient#883]
Hello.

I'm trying to use regclient as a library in an application that deals with OCI layers and images.

It packages applications and pushes them into a registry effectively using the registry as a blob store.

I'm doing a BlobPush operation like this:
```go
func (c *Client) Push(ctx context.Context, d ociv1.Descriptor, src Source) (PushRequest, error) {
	reader, err := src.Reader()
	if err != nil {
		return nil, err
	}

	desc, err := c.rc.BlobPut(ctx, c.ref, c.convertDescriptorToRegClient(d), reader)
	if err != nil {
		return nil, err
	}

	return &pushRequest{
		desc: desc,
		rc:   c.rc,
		ref:  c.ref,
	}, nil
}

```

I have a debug message from the library that looks okay.

```
DESC HERE:  {application/vnd.oci.image.manifest.v1+json sha256:13c30a6e388d5ce8c52596c88af35aa99143351435911536c266cbd572abc792 1019 [] map[] [] <nil>  } https://ghcr.io/v2/skarlso/podinfo-regclient-2/component-descriptors/ocm.software/redis/blobs/upload/1549e248-e1f6-4489-a148-42101a54acd8?digest=sha256%3A13c30a6e388d5ce8c52596c88af35aa99143351435911536c266cbd572abc792
```

This is in the BlobPush part coming back from `blobPutUploadFull`

```go
	fmt.Println("THIS PART 2")
	if tryPut {
		fmt.Println("THIS PART 2.1")
		err = reg.blobPutUploadFull(ctx, r, d, putURL, rdr)
		if err == nil {
			fmt.Println("THIS PART 3")
			fmt.Println("DESC HERE: ", d, putURL)
			return d, nil
		}
```

Yet when I take a look at my User registry, there is no package for `podinfo-regclient-2`.

When I try fetching it with crane I get unknown error:

```
❯ crane blob ghcr.io/skarlso/podinfo-regclient-2/component-descriptors/ocm.software/redis@sha256:13c30a6e388d5ce8c52596c88af35aa99143351435911536c266cbd572abc792
Error: fetching blob ghcr.io/skarlso/podinfo-regclient-2/component-descriptors/ocm.software/redis@sha256:13c30a6e388d5ce8c52596c88af35aa99143351435911536c266cbd572abc792: GET https://ghcr.io/v2/skarlso/podinfo-regclient-2/component-descriptors/ocm.software/redis/blobs/sha256:13c30a6e388d5ce8c52596c88af35aa99143351435911536c266cbd572abc792: BLOB_UNKNOWN: blob unknown to registry
```

I do `Close` the client after the push is done.

What am I missing? Do I need to push some kind of Manifest configuration or something else? I don't really push anything else.

_Edit_: So after _some_ investigation I think I need to push a manifest based on the mediatype. ( I don't know what type I'm getting ).

So something like this:

```go
	isManifest := false
	switch d.MediaType {
	case images.MediaTypeDockerSchema2Manifest, images.MediaTypeDockerSchema2ManifestList,
		ociv1.MediaTypeImageManifest, ociv1.MediaTypeImageIndex:
		isManifest = true
	}
	if isManifest {
		fmt.Println("PUSHING MANIFEST: ", d)
		m, err := manifest.New(manifest.WithDesc(c.convertDescriptorToRegClient(d)), manifest.WithRef(c.ref), manifest.WithRaw(d.Data))
		if err != nil {
			return nil, fmt.Errorf("failed to create a manifest: %w", err)
		}

		if err := c.rc.ManifestPut(ctx, c.ref, m); err != nil {
			return nil, err
		}

		return &pushRequest{
			desc: c.convertDescriptorToRegClient(d),
			rc:   c.rc,
			ref:  c.ref,
		}, nil
	}
```

And I thought this would work. But it's not because it errors with `manifest not set`. 

Sadly, there is nothing about this in the docs on how to proceed or what to do. So what's the general flow to using regclient as a library?

**Comment by sudo-bmitch** [comment]
From the description, it appears you are trying to create an [OCI Artifact](https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidelines-for-artifact-usage).

The `regctl` command has `regctl artifact put` that is implemented at https://github.com/regclient/regclient/blob/d6a5a84740143abaeb72c1892a6659e2aff067ec/cmd/regctl/artifact.go#L667.

**Comment by Skarlso** [comment]
Ah, thank you very much! I'm taking a look!

**Comment by Skarlso** [comment]
So... Previously, I used the docker library ( which was lacking in some sense, no cache, no real retry, etc ). I only initialised the client and did a put. This amount of code looks super excessive. 🤔  do you really think I would need ALL of this?

**Comment by sudo-bmitch** [comment]
The CLI has a lot of features, you'd only include the parts you are using.

**Comment by Skarlso** [comment]
Gotcha. :) thank you for the heads up! :)
