### ISSUE TITLE
Build images for darwin/arm64

### ISSUE THREAD

**Issue by mwgamble** [regclient/regclient#93]
M1 macs are rising in popularity, so it would be good to have native binaries available.

**Comment by sudo-bmitch** [comment]
I can't believe I missed that. Those binaries will be included in the next release. In the meantime, you can pull them from the CI output over here: https://github.com/regclient/regclient/actions/runs/1255265722

**Comment by sudo-bmitch** [comment]
Release 0.3.9 just went out, so these binaries can now be downloaded from the releases page. Thanks for the request and let me know if you encounter any issues!
