### ISSUE TITLE
regctl tag rm seems to leave dangling/empty tag in docker hub

### ISSUE THREAD

**Issue by rgl** [regclient/regclient#96]
At  https://github.com/rgl/example-docker-buildx-go/blob/add-windows/.github/workflows/build.yml#L143 I'm using `regctl tag rm` to remove a tag, and indeed it removes it, but for some reason, they [still appear in docker hub Tags tab, but without any image](https://hub.docker.com/repository/docker/ruilopes/example-docker-buildx-go/tags):

![image](https://user-images.githubusercontent.com/43356/135344660-dd620b90-a3a3-41cd-87e0-369a0c8221d2.png)

Do you have any idea why this is happening?

**Comment by sudo-bmitch** [comment]
Unfortunately, [Docker Hub doesn't support the delete API](https://github.com/docker/hub-feedback/issues/1759). They have been adding a Hub specific API under the paid tier that I'm considering supporting, but the implementation for that is rather kludgy at the moment (the API call goes to a different hostname, and the auth goes through a separate path).

As for why the empty tag is created, the tag delete goes through a couple steps. The first is to try the newer OCI tag delete API. This isn't implemented by many registries yet, so the fallback is to push a blank manifest with a unique digest and then delete that digest. This leaves any other tags on the registry that point to the same manifest, which you want when deleting a single tag. But it has the downside of leaving the blank manifest if the registry rejects the manifest delete API.

**Comment by rgl** [comment]
Thank you for the explanation!

By any chance, do you known whether the GitHub Container registry implements this?

**Comment by sudo-bmitch** [comment]
I did a quick test and only managed to get a "405 Method Not Allowed" from ghcr.io. They do have a delete package role that can be added to a PAT, but I'm guessing that's for a GH specific API.

In case it helps, much of my testing has been with a self hosted registry:

```
docker run -d --restart=unless-stopped --name registry \
  -e "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry" \
  -e "REGISTRY_STORAGE_DELETE_ENABLED=true" \
  -e "REGISTRY_VALIDATION_DISABLED=true" \
  -v "registry-data:/var/lib/registry" \
  -p "127.0.0.1:5000:5000" \
  registry:2
```
